/*
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * This code is generated by a tool and is provided "as is", without warranty of any kind,
 * express or implied, including but not limited to the warranties of merchantability,
 * fitness for a particular purpose and non-infringement.
 * In no event shall the authors or copyright holders be liable for any claim, damages or
 * other liability, whether in an action of contract, tort or otherwise, arising from,
 * out of or in connection with the software or the use or other dealings in the software.
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * */

namespace MureOcart
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.formsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_categoryToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_category_descriptionToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_category_pathToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_category_to_storeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_orderToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_order_historyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_order_productToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_order_totalToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_productToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_product_descriptionToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_product_specialToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_product_to_categoryToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_product_to_storeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_url_aliasToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.button1 = new System.Windows.Forms.Button();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.button2 = new System.Windows.Forms.Button();
            this.label3 = new System.Windows.Forms.Label();
            this.agpc_idprod = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.agpc_idcateg = new System.Windows.Forms.TextBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.agregarCateg = new System.Windows.Forms.Button();
            this.label5 = new System.Windows.Forms.Label();
            this.agc_idcateg = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.agc_idcategpadre = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.agc_nombre = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.agc_desc = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.agc_metadesc = new System.Windows.Forms.TextBox();
            this.agc_metakeys = new System.Windows.Forms.TextBox();
            this.agc_imagen = new System.Windows.Forms.TextBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.agregarImagenProd = new System.Windows.Forms.Button();
            this.label12 = new System.Windows.Forms.Label();
            this.agip_idprod = new System.Windows.Forms.TextBox();
            this.label13 = new System.Windows.Forms.Label();
            this.agip_imagen = new System.Windows.Forms.TextBox();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.agregarProductos = new System.Windows.Forms.Button();
            this.label20 = new System.Windows.Forms.Label();
            this.Orden = new System.Windows.Forms.Label();
            this.agip_orden = new System.Windows.Forms.TextBox();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.actualizarOrden = new System.Windows.Forms.Button();
            this.label21 = new System.Windows.Forms.Label();
            this.ao_orderId = new System.Windows.Forms.TextBox();
            this.label22 = new System.Windows.Forms.Label();
            this.ao_status = new System.Windows.Forms.TextBox();
            this.ao_comentario = new System.Windows.Forms.TextBox();
            this.label23 = new System.Windows.Forms.Label();
            this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            this.ap_archivo = new System.Windows.Forms.TextBox();
            this.button3 = new System.Windows.Forms.Button();
            this.menuStrip1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.formsToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(959, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // formsToolStripMenuItem
            // 
            this.formsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.frmoc_categoryToolStripMenuItem,
            this.frmoc_category_descriptionToolStripMenuItem,
            this.frmoc_category_pathToolStripMenuItem,
            this.frmoc_category_to_storeToolStripMenuItem,
            this.frmoc_orderToolStripMenuItem,
            this.frmoc_order_historyToolStripMenuItem,
            this.frmoc_order_productToolStripMenuItem,
            this.frmoc_order_totalToolStripMenuItem,
            this.frmoc_productToolStripMenuItem,
            this.frmoc_product_descriptionToolStripMenuItem,
            this.frmoc_product_specialToolStripMenuItem,
            this.frmoc_product_to_categoryToolStripMenuItem,
            this.frmoc_product_to_storeToolStripMenuItem,
            this.frmoc_url_aliasToolStripMenuItem});
            this.formsToolStripMenuItem.Name = "formsToolStripMenuItem";
            this.formsToolStripMenuItem.Size = new System.Drawing.Size(53, 20);
            this.formsToolStripMenuItem.Text = "Tablas";
            // 
            // frmoc_categoryToolStripMenuItem
            // 
            this.frmoc_categoryToolStripMenuItem.Name = "frmoc_categoryToolStripMenuItem";
            this.frmoc_categoryToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_categoryToolStripMenuItem.Text = "oc_category";
            this.frmoc_categoryToolStripMenuItem.Click += new System.EventHandler(this.frmoc_categoryToolStripMenuItem_Click);
            // 
            // frmoc_category_descriptionToolStripMenuItem
            // 
            this.frmoc_category_descriptionToolStripMenuItem.Name = "frmoc_category_descriptionToolStripMenuItem";
            this.frmoc_category_descriptionToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_category_descriptionToolStripMenuItem.Text = "oc_category_description";
            this.frmoc_category_descriptionToolStripMenuItem.Click += new System.EventHandler(this.frmoc_category_descriptionToolStripMenuItem_Click);
            // 
            // frmoc_category_pathToolStripMenuItem
            // 
            this.frmoc_category_pathToolStripMenuItem.Name = "frmoc_category_pathToolStripMenuItem";
            this.frmoc_category_pathToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_category_pathToolStripMenuItem.Text = "oc_category_path";
            this.frmoc_category_pathToolStripMenuItem.Click += new System.EventHandler(this.frmoc_category_pathToolStripMenuItem_Click);
            // 
            // frmoc_category_to_storeToolStripMenuItem
            // 
            this.frmoc_category_to_storeToolStripMenuItem.Name = "frmoc_category_to_storeToolStripMenuItem";
            this.frmoc_category_to_storeToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_category_to_storeToolStripMenuItem.Text = "oc_category_to_store";
            this.frmoc_category_to_storeToolStripMenuItem.Click += new System.EventHandler(this.frmoc_category_to_storeToolStripMenuItem_Click);
            // 
            // frmoc_orderToolStripMenuItem
            // 
            this.frmoc_orderToolStripMenuItem.Name = "frmoc_orderToolStripMenuItem";
            this.frmoc_orderToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_orderToolStripMenuItem.Text = "oc_order";
            this.frmoc_orderToolStripMenuItem.Click += new System.EventHandler(this.frmoc_orderToolStripMenuItem_Click);
            // 
            // frmoc_order_historyToolStripMenuItem
            // 
            this.frmoc_order_historyToolStripMenuItem.Name = "frmoc_order_historyToolStripMenuItem";
            this.frmoc_order_historyToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_order_historyToolStripMenuItem.Text = "oc_order_history";
            this.frmoc_order_historyToolStripMenuItem.Click += new System.EventHandler(this.frmoc_order_historyToolStripMenuItem_Click);
            // 
            // frmoc_order_productToolStripMenuItem
            // 
            this.frmoc_order_productToolStripMenuItem.Name = "frmoc_order_productToolStripMenuItem";
            this.frmoc_order_productToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_order_productToolStripMenuItem.Text = "oc_order_product";
            this.frmoc_order_productToolStripMenuItem.Click += new System.EventHandler(this.frmoc_order_productToolStripMenuItem_Click);
            // 
            // frmoc_order_totalToolStripMenuItem
            // 
            this.frmoc_order_totalToolStripMenuItem.Name = "frmoc_order_totalToolStripMenuItem";
            this.frmoc_order_totalToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_order_totalToolStripMenuItem.Text = "oc_order_total";
            this.frmoc_order_totalToolStripMenuItem.Click += new System.EventHandler(this.frmoc_order_totalToolStripMenuItem_Click);
            // 
            // frmoc_productToolStripMenuItem
            // 
            this.frmoc_productToolStripMenuItem.Name = "frmoc_productToolStripMenuItem";
            this.frmoc_productToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_productToolStripMenuItem.Text = "oc_product";
            this.frmoc_productToolStripMenuItem.Click += new System.EventHandler(this.frmoc_productToolStripMenuItem_Click);
            // 
            // frmoc_product_descriptionToolStripMenuItem
            // 
            this.frmoc_product_descriptionToolStripMenuItem.Name = "frmoc_product_descriptionToolStripMenuItem";
            this.frmoc_product_descriptionToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_product_descriptionToolStripMenuItem.Text = "oc_product_description";
            this.frmoc_product_descriptionToolStripMenuItem.Click += new System.EventHandler(this.frmoc_product_descriptionToolStripMenuItem_Click);
            // 
            // frmoc_product_specialToolStripMenuItem
            // 
            this.frmoc_product_specialToolStripMenuItem.Name = "frmoc_product_specialToolStripMenuItem";
            this.frmoc_product_specialToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_product_specialToolStripMenuItem.Text = "oc_product_special";
            this.frmoc_product_specialToolStripMenuItem.Click += new System.EventHandler(this.frmoc_product_specialToolStripMenuItem_Click);
            // 
            // frmoc_product_to_categoryToolStripMenuItem
            // 
            this.frmoc_product_to_categoryToolStripMenuItem.Name = "frmoc_product_to_categoryToolStripMenuItem";
            this.frmoc_product_to_categoryToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_product_to_categoryToolStripMenuItem.Text = "oc_product_to_category";
            this.frmoc_product_to_categoryToolStripMenuItem.Click += new System.EventHandler(this.frmoc_product_to_categoryToolStripMenuItem_Click);
            // 
            // frmoc_product_to_storeToolStripMenuItem
            // 
            this.frmoc_product_to_storeToolStripMenuItem.Name = "frmoc_product_to_storeToolStripMenuItem";
            this.frmoc_product_to_storeToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_product_to_storeToolStripMenuItem.Text = "oc_product_to_store";
            this.frmoc_product_to_storeToolStripMenuItem.Click += new System.EventHandler(this.frmoc_product_to_storeToolStripMenuItem_Click);
            // 
            // frmoc_url_aliasToolStripMenuItem
            // 
            this.frmoc_url_aliasToolStripMenuItem.Name = "frmoc_url_aliasToolStripMenuItem";
            this.frmoc_url_aliasToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_url_aliasToolStripMenuItem.Text = "oc_url_alias";
            this.frmoc_url_aliasToolStripMenuItem.Click += new System.EventHandler(this.frmoc_url_aliasToolStripMenuItem_Click);
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(69, 113);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(70, 23);
            this.button1.TabIndex = 1;
            this.button1.Text = "Set Stock";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // textBox1
            // 
            this.textBox1.Location = new System.Drawing.Point(69, 30);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(70, 20);
            this.textBox1.TabIndex = 2;
            // 
            // textBox2
            // 
            this.textBox2.Location = new System.Drawing.Point(69, 71);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new System.Drawing.Size(70, 20);
            this.textBox2.TabIndex = 3;
            this.textBox2.Text = "10";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(22, 33);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(41, 13);
            this.label1.TabIndex = 4;
            this.label1.Text = "Id Prod";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(22, 74);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(35, 13);
            this.label2.TabIndex = 5;
            this.label2.Text = "Stock";
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.button1);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.textBox1);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.textBox2);
            this.groupBox1.Location = new System.Drawing.Point(542, 273);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(181, 157);
            this.groupBox1.TabIndex = 6;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Set Stock";
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.button2);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.agpc_idprod);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.agpc_idcateg);
            this.groupBox2.Location = new System.Drawing.Point(741, 39);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(206, 157);
            this.groupBox2.TabIndex = 7;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Agregar prod a categoria";
            // 
            // button2
            // 
            this.button2.Location = new System.Drawing.Point(69, 113);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(70, 23);
            this.button2.TabIndex = 1;
            this.button2.Text = "Agregar";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(15, 74);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(47, 13);
            this.label3.TabIndex = 5;
            this.label3.Text = "Id Categ";
            // 
            // agpc_idprod
            // 
            this.agpc_idprod.Location = new System.Drawing.Point(69, 30);
            this.agpc_idprod.Name = "agpc_idprod";
            this.agpc_idprod.Size = new System.Drawing.Size(70, 20);
            this.agpc_idprod.TabIndex = 2;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(15, 33);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(41, 13);
            this.label4.TabIndex = 4;
            this.label4.Text = "Id Prod";
            // 
            // agpc_idcateg
            // 
            this.agpc_idcateg.Location = new System.Drawing.Point(69, 71);
            this.agpc_idcateg.Name = "agpc_idcateg";
            this.agpc_idcateg.Size = new System.Drawing.Size(70, 20);
            this.agpc_idcateg.TabIndex = 3;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.agc_imagen);
            this.groupBox3.Controls.Add(this.agc_metakeys);
            this.groupBox3.Controls.Add(this.agc_metadesc);
            this.groupBox3.Controls.Add(this.label11);
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.label9);
            this.groupBox3.Controls.Add(this.agc_desc);
            this.groupBox3.Controls.Add(this.label8);
            this.groupBox3.Controls.Add(this.agc_nombre);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Controls.Add(this.agregarCateg);
            this.groupBox3.Controls.Add(this.label5);
            this.groupBox3.Controls.Add(this.agc_idcateg);
            this.groupBox3.Controls.Add(this.label6);
            this.groupBox3.Controls.Add(this.agc_idcategpadre);
            this.groupBox3.Location = new System.Drawing.Point(12, 39);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(247, 322);
            this.groupBox3.TabIndex = 8;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Agregar categoría";
            // 
            // agregarCateg
            // 
            this.agregarCateg.Location = new System.Drawing.Point(103, 277);
            this.agregarCateg.Name = "agregarCateg";
            this.agregarCateg.Size = new System.Drawing.Size(70, 23);
            this.agregarCateg.TabIndex = 1;
            this.agregarCateg.Text = "Agregar";
            this.agregarCateg.UseVisualStyleBackColor = true;
            this.agregarCateg.Click += new System.EventHandler(this.agregarCateg_Click);
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(16, 67);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(77, 13);
            this.label5.TabIndex = 5;
            this.label5.Text = "Id Categ padre";
            // 
            // agc_idcateg
            // 
            this.agc_idcateg.Location = new System.Drawing.Point(103, 30);
            this.agc_idcateg.Name = "agc_idcateg";
            this.agc_idcateg.Size = new System.Drawing.Size(70, 20);
            this.agc_idcateg.TabIndex = 2;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(16, 33);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(64, 13);
            this.label6.TabIndex = 4;
            this.label6.Text = "Id Categoria";
            // 
            // agc_idcategpadre
            // 
            this.agc_idcategpadre.Location = new System.Drawing.Point(103, 64);
            this.agc_idcategpadre.Name = "agc_idcategpadre";
            this.agc_idcategpadre.Size = new System.Drawing.Size(70, 20);
            this.agc_idcategpadre.TabIndex = 3;
            this.agc_idcategpadre.Text = "0";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(16, 101);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(44, 13);
            this.label7.TabIndex = 6;
            this.label7.Text = "Nombre";
            // 
            // agc_nombre
            // 
            this.agc_nombre.Location = new System.Drawing.Point(103, 98);
            this.agc_nombre.Name = "agc_nombre";
            this.agc_nombre.Size = new System.Drawing.Size(132, 20);
            this.agc_nombre.TabIndex = 7;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(16, 135);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(63, 13);
            this.label8.TabIndex = 8;
            this.label8.Text = "Descripcion";
            // 
            // agc_desc
            // 
            this.agc_desc.Location = new System.Drawing.Point(103, 132);
            this.agc_desc.Name = "agc_desc";
            this.agc_desc.Size = new System.Drawing.Size(132, 20);
            this.agc_desc.TabIndex = 9;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(16, 169);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(62, 13);
            this.label9.TabIndex = 10;
            this.label9.Text = "Meta Desc.";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(16, 203);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(57, 13);
            this.label10.TabIndex = 11;
            this.label10.Text = "Meta Keys";
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(18, 237);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(42, 13);
            this.label11.TabIndex = 12;
            this.label11.Text = "Imagen";
            // 
            // agc_metadesc
            // 
            this.agc_metadesc.Location = new System.Drawing.Point(103, 166);
            this.agc_metadesc.Name = "agc_metadesc";
            this.agc_metadesc.Size = new System.Drawing.Size(132, 20);
            this.agc_metadesc.TabIndex = 13;
            // 
            // agc_metakeys
            // 
            this.agc_metakeys.Location = new System.Drawing.Point(103, 200);
            this.agc_metakeys.Name = "agc_metakeys";
            this.agc_metakeys.Size = new System.Drawing.Size(132, 20);
            this.agc_metakeys.TabIndex = 14;
            // 
            // agc_imagen
            // 
            this.agc_imagen.Location = new System.Drawing.Point(103, 234);
            this.agc_imagen.Name = "agc_imagen";
            this.agc_imagen.Size = new System.Drawing.Size(132, 20);
            this.agc_imagen.TabIndex = 15;
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.agip_orden);
            this.groupBox4.Controls.Add(this.Orden);
            this.groupBox4.Controls.Add(this.agregarImagenProd);
            this.groupBox4.Controls.Add(this.label12);
            this.groupBox4.Controls.Add(this.agip_idprod);
            this.groupBox4.Controls.Add(this.label13);
            this.groupBox4.Controls.Add(this.agip_imagen);
            this.groupBox4.Location = new System.Drawing.Point(542, 39);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(181, 207);
            this.groupBox4.TabIndex = 9;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Agregar img a producto";
            // 
            // agregarImagenProd
            // 
            this.agregarImagenProd.Location = new System.Drawing.Point(55, 151);
            this.agregarImagenProd.Name = "agregarImagenProd";
            this.agregarImagenProd.Size = new System.Drawing.Size(70, 23);
            this.agregarImagenProd.TabIndex = 1;
            this.agregarImagenProd.Text = "Agregar";
            this.agregarImagenProd.UseVisualStyleBackColor = true;
            this.agregarImagenProd.Click += new System.EventHandler(this.agregarImagenProd_Click);
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(8, 74);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(42, 13);
            this.label12.TabIndex = 5;
            this.label12.Text = "Imagen";
            // 
            // agip_idprod
            // 
            this.agip_idprod.Location = new System.Drawing.Point(55, 30);
            this.agip_idprod.Name = "agip_idprod";
            this.agip_idprod.Size = new System.Drawing.Size(70, 20);
            this.agip_idprod.TabIndex = 2;
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Location = new System.Drawing.Point(8, 33);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(41, 13);
            this.label13.TabIndex = 4;
            this.label13.Text = "Id Prod";
            // 
            // agip_imagen
            // 
            this.agip_imagen.Location = new System.Drawing.Point(55, 71);
            this.agip_imagen.Name = "agip_imagen";
            this.agip_imagen.Size = new System.Drawing.Size(120, 20);
            this.agip_imagen.TabIndex = 3;
            // 
            // groupBox5
            // 
            this.groupBox5.Controls.Add(this.button3);
            this.groupBox5.Controls.Add(this.ap_archivo);
            this.groupBox5.Controls.Add(this.agregarProductos);
            this.groupBox5.Controls.Add(this.label20);
            this.groupBox5.Location = new System.Drawing.Point(276, 39);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(248, 233);
            this.groupBox5.TabIndex = 10;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Agregar producto";
            // 
            // agregarProductos
            // 
            this.agregarProductos.Enabled = false;
            this.agregarProductos.Location = new System.Drawing.Point(19, 125);
            this.agregarProductos.Name = "agregarProductos";
            this.agregarProductos.Size = new System.Drawing.Size(118, 23);
            this.agregarProductos.TabIndex = 1;
            this.agregarProductos.Text = "Agregar Productos";
            this.agregarProductos.UseVisualStyleBackColor = true;
            this.agregarProductos.Click += new System.EventHandler(this.agregarProductos_Click);
            // 
            // label20
            // 
            this.label20.AutoSize = true;
            this.label20.Location = new System.Drawing.Point(16, 33);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(62, 13);
            this.label20.TabIndex = 4;
            this.label20.Text = "archivo csv";
            // 
            // Orden
            // 
            this.Orden.AutoSize = true;
            this.Orden.Location = new System.Drawing.Point(8, 114);
            this.Orden.Name = "Orden";
            this.Orden.Size = new System.Drawing.Size(36, 13);
            this.Orden.TabIndex = 6;
            this.Orden.Text = "Orden";
            // 
            // agip_orden
            // 
            this.agip_orden.Location = new System.Drawing.Point(55, 111);
            this.agip_orden.Name = "agip_orden";
            this.agip_orden.Size = new System.Drawing.Size(70, 20);
            this.agip_orden.TabIndex = 7;
            this.agip_orden.Text = "1";
            // 
            // groupBox6
            // 
            this.groupBox6.Controls.Add(this.label23);
            this.groupBox6.Controls.Add(this.ao_comentario);
            this.groupBox6.Controls.Add(this.actualizarOrden);
            this.groupBox6.Controls.Add(this.label21);
            this.groupBox6.Controls.Add(this.ao_orderId);
            this.groupBox6.Controls.Add(this.label22);
            this.groupBox6.Controls.Add(this.ao_status);
            this.groupBox6.Location = new System.Drawing.Point(741, 226);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(206, 207);
            this.groupBox6.TabIndex = 8;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "Actualizar Orden";
            // 
            // actualizarOrden
            // 
            this.actualizarOrden.Location = new System.Drawing.Point(71, 160);
            this.actualizarOrden.Name = "actualizarOrden";
            this.actualizarOrden.Size = new System.Drawing.Size(70, 23);
            this.actualizarOrden.TabIndex = 1;
            this.actualizarOrden.Text = "Actualizar";
            this.actualizarOrden.UseVisualStyleBackColor = true;
            this.actualizarOrden.Click += new System.EventHandler(this.actualizarOrden_Click);
            // 
            // label21
            // 
            this.label21.AutoSize = true;
            this.label21.Location = new System.Drawing.Point(11, 74);
            this.label21.Name = "label21";
            this.label21.Size = new System.Drawing.Size(37, 13);
            this.label21.TabIndex = 5;
            this.label21.Text = "Status";
            // 
            // ao_orderId
            // 
            this.ao_orderId.Location = new System.Drawing.Point(71, 30);
            this.ao_orderId.Name = "ao_orderId";
            this.ao_orderId.Size = new System.Drawing.Size(70, 20);
            this.ao_orderId.TabIndex = 2;
            // 
            // label22
            // 
            this.label22.AutoSize = true;
            this.label22.Location = new System.Drawing.Point(11, 33);
            this.label22.Name = "label22";
            this.label22.Size = new System.Drawing.Size(48, 13);
            this.label22.TabIndex = 4;
            this.label22.Text = "Id Orden";
            // 
            // ao_status
            // 
            this.ao_status.Location = new System.Drawing.Point(71, 71);
            this.ao_status.Name = "ao_status";
            this.ao_status.Size = new System.Drawing.Size(70, 20);
            this.ao_status.TabIndex = 3;
            // 
            // ao_comentario
            // 
            this.ao_comentario.Location = new System.Drawing.Point(71, 114);
            this.ao_comentario.Name = "ao_comentario";
            this.ao_comentario.Size = new System.Drawing.Size(120, 20);
            this.ao_comentario.TabIndex = 8;
            // 
            // label23
            // 
            this.label23.AutoSize = true;
            this.label23.Location = new System.Drawing.Point(11, 117);
            this.label23.Name = "label23";
            this.label23.Size = new System.Drawing.Size(60, 13);
            this.label23.TabIndex = 9;
            this.label23.Text = "Comentario";
            // 
            // openFileDialog1
            // 
            this.openFileDialog1.FileName = "openFileDialog1";
            // 
            // ap_archivo
            // 
            this.ap_archivo.Location = new System.Drawing.Point(19, 59);
            this.ap_archivo.Name = "ap_archivo";
            this.ap_archivo.Size = new System.Drawing.Size(223, 20);
            this.ap_archivo.TabIndex = 5;
            // 
            // button3
            // 
            this.button3.Location = new System.Drawing.Point(19, 85);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(118, 23);
            this.button3.TabIndex = 6;
            this.button3.Text = "Elegir Archivo";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(959, 464);
            this.Controls.Add(this.groupBox6);
            this.Controls.Add(this.groupBox5);
            this.Controls.Add(this.groupBox4);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "frmMain";
            this.Text = "Main Form";
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem formsToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_categoryToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_category_descriptionToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_category_pathToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_category_to_storeToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_orderToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_order_historyToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_order_productToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_order_totalToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_productToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_product_descriptionToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_product_specialToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_product_to_categoryToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_product_to_storeToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_url_aliasToolStripMenuItem;
    private System.Windows.Forms.Button button1;
    private System.Windows.Forms.TextBox textBox1;
    private System.Windows.Forms.TextBox textBox2;
    private System.Windows.Forms.Label label1;
    private System.Windows.Forms.Label label2;
    private System.Windows.Forms.GroupBox groupBox1;
    private System.Windows.Forms.GroupBox groupBox2;
    private System.Windows.Forms.Button button2;
    private System.Windows.Forms.Label label3;
    private System.Windows.Forms.TextBox agpc_idprod;
    private System.Windows.Forms.Label label4;
    private System.Windows.Forms.TextBox agpc_idcateg;
    private System.Windows.Forms.GroupBox groupBox3;
    private System.Windows.Forms.TextBox agc_imagen;
    private System.Windows.Forms.TextBox agc_metakeys;
    private System.Windows.Forms.TextBox agc_metadesc;
    private System.Windows.Forms.Label label11;
    private System.Windows.Forms.Label label10;
    private System.Windows.Forms.Label label9;
    private System.Windows.Forms.TextBox agc_desc;
    private System.Windows.Forms.Label label8;
    private System.Windows.Forms.TextBox agc_nombre;
    private System.Windows.Forms.Label label7;
    private System.Windows.Forms.Button agregarCateg;
    private System.Windows.Forms.Label label5;
    private System.Windows.Forms.TextBox agc_idcateg;
    private System.Windows.Forms.Label label6;
    private System.Windows.Forms.TextBox agc_idcategpadre;
    private System.Windows.Forms.GroupBox groupBox4;
    private System.Windows.Forms.TextBox agip_orden;
    private System.Windows.Forms.Label Orden;
    private System.Windows.Forms.Button agregarImagenProd;
    private System.Windows.Forms.Label label12;
    private System.Windows.Forms.TextBox agip_idprod;
    private System.Windows.Forms.Label label13;
    private System.Windows.Forms.TextBox agip_imagen;
    private System.Windows.Forms.GroupBox groupBox5;
    private System.Windows.Forms.Button agregarProductos;
    private System.Windows.Forms.Label label20;
    private System.Windows.Forms.GroupBox groupBox6;
    private System.Windows.Forms.Label label23;
    private System.Windows.Forms.TextBox ao_comentario;
    private System.Windows.Forms.Button actualizarOrden;
    private System.Windows.Forms.Label label21;
    private System.Windows.Forms.TextBox ao_orderId;
    private System.Windows.Forms.Label label22;
    private System.Windows.Forms.TextBox ao_status;
    private System.Windows.Forms.Button button3;
    private System.Windows.Forms.TextBox ap_archivo;
    private System.Windows.Forms.OpenFileDialog openFileDialog1;

    }
}
