/*
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * This code is generated by a tool and is provided "as is", without warranty of any kind,
 * express or implied, including but not limited to the warranties of merchantability,
 * fitness for a particular purpose and non-infringement.
 * In no event shall the authors or copyright holders be liable for any claim, damages or
 * other liability, whether in an action of contract, tort or otherwise, arising from,
 * out of or in connection with the software or the use or other dealings in the software.
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * */

namespace MureOcart
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.formsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_categoryToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_category_descriptionToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_category_pathToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_category_to_storeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_orderToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_order_historyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_order_productToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_order_totalToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_productToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_product_descriptionToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_product_specialToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_product_to_categoryToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_product_to_storeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmoc_url_aliasToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.button1 = new System.Windows.Forms.Button();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.menuStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.formsToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(858, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // formsToolStripMenuItem
            // 
            this.formsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.frmoc_categoryToolStripMenuItem,
            this.frmoc_category_descriptionToolStripMenuItem,
            this.frmoc_category_pathToolStripMenuItem,
            this.frmoc_category_to_storeToolStripMenuItem,
            this.frmoc_orderToolStripMenuItem,
            this.frmoc_order_historyToolStripMenuItem,
            this.frmoc_order_productToolStripMenuItem,
            this.frmoc_order_totalToolStripMenuItem,
            this.frmoc_productToolStripMenuItem,
            this.frmoc_product_descriptionToolStripMenuItem,
            this.frmoc_product_specialToolStripMenuItem,
            this.frmoc_product_to_categoryToolStripMenuItem,
            this.frmoc_product_to_storeToolStripMenuItem,
            this.frmoc_url_aliasToolStripMenuItem});
            this.formsToolStripMenuItem.Name = "formsToolStripMenuItem";
            this.formsToolStripMenuItem.Size = new System.Drawing.Size(52, 20);
            this.formsToolStripMenuItem.Text = "Forms";
            // 
            // frmoc_categoryToolStripMenuItem
            // 
            this.frmoc_categoryToolStripMenuItem.Name = "frmoc_categoryToolStripMenuItem";
            this.frmoc_categoryToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_categoryToolStripMenuItem.Text = "oc_category";
            this.frmoc_categoryToolStripMenuItem.Click += new System.EventHandler(this.frmoc_categoryToolStripMenuItem_Click);
            // 
            // frmoc_category_descriptionToolStripMenuItem
            // 
            this.frmoc_category_descriptionToolStripMenuItem.Name = "frmoc_category_descriptionToolStripMenuItem";
            this.frmoc_category_descriptionToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_category_descriptionToolStripMenuItem.Text = "oc_category_description";
            this.frmoc_category_descriptionToolStripMenuItem.Click += new System.EventHandler(this.frmoc_category_descriptionToolStripMenuItem_Click);
            // 
            // frmoc_category_pathToolStripMenuItem
            // 
            this.frmoc_category_pathToolStripMenuItem.Name = "frmoc_category_pathToolStripMenuItem";
            this.frmoc_category_pathToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_category_pathToolStripMenuItem.Text = "oc_category_path";
            this.frmoc_category_pathToolStripMenuItem.Click += new System.EventHandler(this.frmoc_category_pathToolStripMenuItem_Click);
            // 
            // frmoc_category_to_storeToolStripMenuItem
            // 
            this.frmoc_category_to_storeToolStripMenuItem.Name = "frmoc_category_to_storeToolStripMenuItem";
            this.frmoc_category_to_storeToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_category_to_storeToolStripMenuItem.Text = "oc_category_to_store";
            this.frmoc_category_to_storeToolStripMenuItem.Click += new System.EventHandler(this.frmoc_category_to_storeToolStripMenuItem_Click);
            // 
            // frmoc_orderToolStripMenuItem
            // 
            this.frmoc_orderToolStripMenuItem.Name = "frmoc_orderToolStripMenuItem";
            this.frmoc_orderToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_orderToolStripMenuItem.Text = "oc_order";
            this.frmoc_orderToolStripMenuItem.Click += new System.EventHandler(this.frmoc_orderToolStripMenuItem_Click);
            // 
            // frmoc_order_historyToolStripMenuItem
            // 
            this.frmoc_order_historyToolStripMenuItem.Name = "frmoc_order_historyToolStripMenuItem";
            this.frmoc_order_historyToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_order_historyToolStripMenuItem.Text = "oc_order_history";
            this.frmoc_order_historyToolStripMenuItem.Click += new System.EventHandler(this.frmoc_order_historyToolStripMenuItem_Click);
            // 
            // frmoc_order_productToolStripMenuItem
            // 
            this.frmoc_order_productToolStripMenuItem.Name = "frmoc_order_productToolStripMenuItem";
            this.frmoc_order_productToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_order_productToolStripMenuItem.Text = "oc_order_product";
            this.frmoc_order_productToolStripMenuItem.Click += new System.EventHandler(this.frmoc_order_productToolStripMenuItem_Click);
            // 
            // frmoc_order_totalToolStripMenuItem
            // 
            this.frmoc_order_totalToolStripMenuItem.Name = "frmoc_order_totalToolStripMenuItem";
            this.frmoc_order_totalToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_order_totalToolStripMenuItem.Text = "oc_order_total";
            this.frmoc_order_totalToolStripMenuItem.Click += new System.EventHandler(this.frmoc_order_totalToolStripMenuItem_Click);
            // 
            // frmoc_productToolStripMenuItem
            // 
            this.frmoc_productToolStripMenuItem.Name = "frmoc_productToolStripMenuItem";
            this.frmoc_productToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_productToolStripMenuItem.Text = "oc_product";
            this.frmoc_productToolStripMenuItem.Click += new System.EventHandler(this.frmoc_productToolStripMenuItem_Click);
            // 
            // frmoc_product_descriptionToolStripMenuItem
            // 
            this.frmoc_product_descriptionToolStripMenuItem.Name = "frmoc_product_descriptionToolStripMenuItem";
            this.frmoc_product_descriptionToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_product_descriptionToolStripMenuItem.Text = "oc_product_description";
            this.frmoc_product_descriptionToolStripMenuItem.Click += new System.EventHandler(this.frmoc_product_descriptionToolStripMenuItem_Click);
            // 
            // frmoc_product_specialToolStripMenuItem
            // 
            this.frmoc_product_specialToolStripMenuItem.Name = "frmoc_product_specialToolStripMenuItem";
            this.frmoc_product_specialToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_product_specialToolStripMenuItem.Text = "oc_product_special";
            this.frmoc_product_specialToolStripMenuItem.Click += new System.EventHandler(this.frmoc_product_specialToolStripMenuItem_Click);
            // 
            // frmoc_product_to_categoryToolStripMenuItem
            // 
            this.frmoc_product_to_categoryToolStripMenuItem.Name = "frmoc_product_to_categoryToolStripMenuItem";
            this.frmoc_product_to_categoryToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_product_to_categoryToolStripMenuItem.Text = "oc_product_to_category";
            this.frmoc_product_to_categoryToolStripMenuItem.Click += new System.EventHandler(this.frmoc_product_to_categoryToolStripMenuItem_Click);
            // 
            // frmoc_product_to_storeToolStripMenuItem
            // 
            this.frmoc_product_to_storeToolStripMenuItem.Name = "frmoc_product_to_storeToolStripMenuItem";
            this.frmoc_product_to_storeToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_product_to_storeToolStripMenuItem.Text = "oc_product_to_store";
            this.frmoc_product_to_storeToolStripMenuItem.Click += new System.EventHandler(this.frmoc_product_to_storeToolStripMenuItem_Click);
            // 
            // frmoc_url_aliasToolStripMenuItem
            // 
            this.frmoc_url_aliasToolStripMenuItem.Name = "frmoc_url_aliasToolStripMenuItem";
            this.frmoc_url_aliasToolStripMenuItem.Size = new System.Drawing.Size(202, 22);
            this.frmoc_url_aliasToolStripMenuItem.Text = "oc_url_alias";
            this.frmoc_url_aliasToolStripMenuItem.Click += new System.EventHandler(this.frmoc_url_aliasToolStripMenuItem_Click);
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(238, 40);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(75, 23);
            this.button1.TabIndex = 1;
            this.button1.Text = "Set Stock";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // textBox1
            // 
            this.textBox1.Location = new System.Drawing.Point(71, 42);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(70, 20);
            this.textBox1.TabIndex = 2;
            // 
            // textBox2
            // 
            this.textBox2.Location = new System.Drawing.Point(161, 42);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new System.Drawing.Size(53, 20);
            this.textBox2.TabIndex = 3;
            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(858, 405);
            this.Controls.Add(this.textBox2);
            this.Controls.Add(this.textBox1);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "frmMain";
            this.Text = "Main Form";
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem formsToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_categoryToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_category_descriptionToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_category_pathToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_category_to_storeToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_orderToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_order_historyToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_order_productToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_order_totalToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_productToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_product_descriptionToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_product_specialToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_product_to_categoryToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_product_to_storeToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmoc_url_aliasToolStripMenuItem;
    private System.Windows.Forms.Button button1;
    private System.Windows.Forms.TextBox textBox1;
    private System.Windows.Forms.TextBox textBox2;

    }
}
