/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;

namespace MureOcart
{
	public partial class frmoc_order_total : Form
	{
		private Model1Entities ctx;
		
		public frmoc_order_total()
		{
			InitializeComponent();
		}
		
		private void frmoc_order_total_Load(object sender, EventArgs e)
		{
			ctx = new Model1Entities();
			ctx.oc_order_total.Load();
			BindingList<oc_order_total> _entities = ctx.oc_order_total.Local.ToBindingList();
			oc_order_totalBindingSource.DataSource = _entities;
			this.order_total_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_order_totalBindingSource, "order_total_id", true ));
			this.order_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_order_totalBindingSource, "order_id", true ));
			this.codeTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_order_totalBindingSource, "code", true ));
			this.titleTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_order_totalBindingSource, "title", true ));
			this.textTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_order_totalBindingSource, "text", true ));
			this.valueTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_order_totalBindingSource, "value", true ));
			this.sort_orderTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_order_totalBindingSource, "sort_order", true ));
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			oc_order_totalBindingSource.EndEdit();
			ctx.SaveChanges();
			
		}
		
		private void frmoc_order_total_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void order_total_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( order_total_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( order_total_idTextBox, "The field order_total_id is required" ); 
			}
			int v;
			string s = order_total_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( order_total_idTextBox, "The field order_total_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( order_total_idTextBox, "" ); } 
		}
		
		private void order_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( order_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( order_idTextBox, "The field order_id is required" ); 
			}
			int v;
			string s = order_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( order_idTextBox, "The field order_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( order_idTextBox, "" ); } 
		}
		
		private void codeTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( codeTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( codeTextBox, "The field code is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( codeTextBox, "" ); } 
		}
		
		private void titleTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( titleTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( titleTextBox, "The field title is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( titleTextBox, "" ); } 
		}
		
		private void textTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( textTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( textTextBox, "The field text is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( textTextBox, "" ); } 
		}
		
		private void valueTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( valueTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( valueTextBox, "The field value is required" ); 
			}
			double v;
			string s = valueTextBox.Text;
			if( !double.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( valueTextBox, "The field value must be double." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( valueTextBox, "" ); } 
		}
		
		private void sort_orderTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( sort_orderTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( sort_orderTextBox, "The field sort_order is required" ); 
			}
			int v;
			string s = sort_orderTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( sort_orderTextBox, "The field sort_order must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( sort_orderTextBox, "" ); } 
		}
		
		
		
		
		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			oc_order_totalBindingSource.AddNew();
		}
	}
}
