/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

namespace MureOcart
{
	partial class frmoc_order
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmoc_order));
            this.bindingNavigator1 = new System.Windows.Forms.BindingNavigator(this.components);
            this.bindingNavigatorCountItem = new System.Windows.Forms.ToolStripLabel();
            this.bindingNavigatorDeleteItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMoveFirstItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMovePreviousItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorSeparator = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorPositionItem = new System.Windows.Forms.ToolStripTextBox();
            this.bindingNavigatorSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorMoveNextItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMoveLastItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorAddNewItem = new System.Windows.Forms.ToolStripButton();
            this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
            this.oc_orderBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.Panel1 = new System.Windows.Forms.Panel();
            this.order_idLabel = new System.Windows.Forms.Label();
            this.order_idTextBox = new System.Windows.Forms.TextBox();
            this.invoice_noLabel = new System.Windows.Forms.Label();
            this.invoice_noTextBox = new System.Windows.Forms.TextBox();
            this.invoice_prefixLabel = new System.Windows.Forms.Label();
            this.invoice_prefixTextBox = new System.Windows.Forms.TextBox();
            this.store_idLabel = new System.Windows.Forms.Label();
            this.store_idTextBox = new System.Windows.Forms.TextBox();
            this.store_nameLabel = new System.Windows.Forms.Label();
            this.store_nameTextBox = new System.Windows.Forms.TextBox();
            this.store_urlLabel = new System.Windows.Forms.Label();
            this.store_urlTextBox = new System.Windows.Forms.TextBox();
            this.customer_idLabel = new System.Windows.Forms.Label();
            this.customer_idTextBox = new System.Windows.Forms.TextBox();
            this.customer_group_idLabel = new System.Windows.Forms.Label();
            this.customer_group_idTextBox = new System.Windows.Forms.TextBox();
            this.firstnameLabel = new System.Windows.Forms.Label();
            this.firstnameTextBox = new System.Windows.Forms.TextBox();
            this.lastnameLabel = new System.Windows.Forms.Label();
            this.lastnameTextBox = new System.Windows.Forms.TextBox();
            this.emailLabel = new System.Windows.Forms.Label();
            this.emailTextBox = new System.Windows.Forms.TextBox();
            this.telephoneLabel = new System.Windows.Forms.Label();
            this.telephoneTextBox = new System.Windows.Forms.TextBox();
            this.faxLabel = new System.Windows.Forms.Label();
            this.faxTextBox = new System.Windows.Forms.TextBox();
            this.payment_firstnameLabel = new System.Windows.Forms.Label();
            this.payment_firstnameTextBox = new System.Windows.Forms.TextBox();
            this.payment_lastnameLabel = new System.Windows.Forms.Label();
            this.payment_lastnameTextBox = new System.Windows.Forms.TextBox();
            this.payment_companyLabel = new System.Windows.Forms.Label();
            this.payment_companyTextBox = new System.Windows.Forms.TextBox();
            this.payment_company_idLabel = new System.Windows.Forms.Label();
            this.payment_company_idTextBox = new System.Windows.Forms.TextBox();
            this.payment_tax_idLabel = new System.Windows.Forms.Label();
            this.payment_tax_idTextBox = new System.Windows.Forms.TextBox();
            this.payment_address_1Label = new System.Windows.Forms.Label();
            this.payment_address_1TextBox = new System.Windows.Forms.TextBox();
            this.payment_address_2Label = new System.Windows.Forms.Label();
            this.payment_address_2TextBox = new System.Windows.Forms.TextBox();
            this.payment_cityLabel = new System.Windows.Forms.Label();
            this.payment_cityTextBox = new System.Windows.Forms.TextBox();
            this.payment_postcodeLabel = new System.Windows.Forms.Label();
            this.payment_postcodeTextBox = new System.Windows.Forms.TextBox();
            this.payment_countryLabel = new System.Windows.Forms.Label();
            this.payment_countryTextBox = new System.Windows.Forms.TextBox();
            this.payment_country_idLabel = new System.Windows.Forms.Label();
            this.payment_country_idTextBox = new System.Windows.Forms.TextBox();
            this.payment_zoneLabel = new System.Windows.Forms.Label();
            this.payment_zoneTextBox = new System.Windows.Forms.TextBox();
            this.payment_zone_idLabel = new System.Windows.Forms.Label();
            this.payment_zone_idTextBox = new System.Windows.Forms.TextBox();
            this.payment_address_formatLabel = new System.Windows.Forms.Label();
            this.payment_address_formatTextBox = new System.Windows.Forms.TextBox();
            this.payment_methodLabel = new System.Windows.Forms.Label();
            this.payment_methodTextBox = new System.Windows.Forms.TextBox();
            this.payment_codeLabel = new System.Windows.Forms.Label();
            this.payment_codeTextBox = new System.Windows.Forms.TextBox();
            this.shipping_firstnameLabel = new System.Windows.Forms.Label();
            this.shipping_firstnameTextBox = new System.Windows.Forms.TextBox();
            this.shipping_lastnameLabel = new System.Windows.Forms.Label();
            this.shipping_lastnameTextBox = new System.Windows.Forms.TextBox();
            this.shipping_companyLabel = new System.Windows.Forms.Label();
            this.shipping_companyTextBox = new System.Windows.Forms.TextBox();
            this.shipping_address_1Label = new System.Windows.Forms.Label();
            this.shipping_address_1TextBox = new System.Windows.Forms.TextBox();
            this.shipping_address_2Label = new System.Windows.Forms.Label();
            this.shipping_address_2TextBox = new System.Windows.Forms.TextBox();
            this.shipping_cityLabel = new System.Windows.Forms.Label();
            this.shipping_cityTextBox = new System.Windows.Forms.TextBox();
            this.shipping_postcodeLabel = new System.Windows.Forms.Label();
            this.shipping_postcodeTextBox = new System.Windows.Forms.TextBox();
            this.shipping_countryLabel = new System.Windows.Forms.Label();
            this.shipping_countryTextBox = new System.Windows.Forms.TextBox();
            this.shipping_country_idLabel = new System.Windows.Forms.Label();
            this.shipping_country_idTextBox = new System.Windows.Forms.TextBox();
            this.shipping_zoneLabel = new System.Windows.Forms.Label();
            this.shipping_zoneTextBox = new System.Windows.Forms.TextBox();
            this.shipping_zone_idLabel = new System.Windows.Forms.Label();
            this.shipping_zone_idTextBox = new System.Windows.Forms.TextBox();
            this.shipping_address_formatLabel = new System.Windows.Forms.Label();
            this.shipping_address_formatTextBox = new System.Windows.Forms.TextBox();
            this.shipping_methodLabel = new System.Windows.Forms.Label();
            this.shipping_methodTextBox = new System.Windows.Forms.TextBox();
            this.shipping_codeLabel = new System.Windows.Forms.Label();
            this.shipping_codeTextBox = new System.Windows.Forms.TextBox();
            this.commentLabel = new System.Windows.Forms.Label();
            this.commentTextBox = new System.Windows.Forms.TextBox();
            this.totalLabel = new System.Windows.Forms.Label();
            this.totalTextBox = new System.Windows.Forms.TextBox();
            this.order_status_idLabel = new System.Windows.Forms.Label();
            this.order_status_idTextBox = new System.Windows.Forms.TextBox();
            this.affiliate_idLabel = new System.Windows.Forms.Label();
            this.affiliate_idTextBox = new System.Windows.Forms.TextBox();
            this.commissionLabel = new System.Windows.Forms.Label();
            this.commissionTextBox = new System.Windows.Forms.TextBox();
            this.language_idLabel = new System.Windows.Forms.Label();
            this.language_idTextBox = new System.Windows.Forms.TextBox();
            this.currency_idLabel = new System.Windows.Forms.Label();
            this.currency_idTextBox = new System.Windows.Forms.TextBox();
            this.currency_codeLabel = new System.Windows.Forms.Label();
            this.currency_codeTextBox = new System.Windows.Forms.TextBox();
            this.currency_valueLabel = new System.Windows.Forms.Label();
            this.currency_valueTextBox = new System.Windows.Forms.TextBox();
            this.ipLabel = new System.Windows.Forms.Label();
            this.ipTextBox = new System.Windows.Forms.TextBox();
            this.forwarded_ipLabel = new System.Windows.Forms.Label();
            this.forwarded_ipTextBox = new System.Windows.Forms.TextBox();
            this.user_agentLabel = new System.Windows.Forms.Label();
            this.user_agentTextBox = new System.Windows.Forms.TextBox();
            this.accept_languageLabel = new System.Windows.Forms.Label();
            this.accept_languageTextBox = new System.Windows.Forms.TextBox();
            this.date_addedLabel = new System.Windows.Forms.Label();
            this.date_added_dateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.date_modifiedLabel = new System.Windows.Forms.Label();
            this.date_modified_dateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.panel3 = new System.Windows.Forms.Panel();
            this.panel4 = new System.Windows.Forms.Panel();
            this.panel5 = new System.Windows.Forms.Panel();
            this.panel6 = new System.Windows.Forms.Panel();
            ((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).BeginInit();
            this.bindingNavigator1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.oc_orderBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.Panel1.SuspendLayout();
            this.panel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // bindingNavigator1
            // 
            this.bindingNavigator1.AddNewItem = null;
            this.bindingNavigator1.BindingSource = this.oc_orderBindingSource;
            this.bindingNavigator1.CountItem = this.bindingNavigatorCountItem;
            this.bindingNavigator1.DeleteItem = this.bindingNavigatorDeleteItem;
            this.bindingNavigator1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.bindingNavigatorMoveFirstItem,
            this.bindingNavigatorMovePreviousItem,
            this.bindingNavigatorSeparator,
            this.bindingNavigatorPositionItem,
            this.bindingNavigatorCountItem,
            this.bindingNavigatorSeparator1,
            this.bindingNavigatorMoveNextItem,
            this.bindingNavigatorMoveLastItem,
            this.bindingNavigatorSeparator2,
            this.bindingNavigatorAddNewItem,
            this.bindingNavigatorDeleteItem,
            this.toolStripButton1});
            this.bindingNavigator1.Location = new System.Drawing.Point(0, 0);
            this.bindingNavigator1.MoveFirstItem = this.bindingNavigatorMoveFirstItem;
            this.bindingNavigator1.MoveLastItem = this.bindingNavigatorMoveLastItem;
            this.bindingNavigator1.MoveNextItem = this.bindingNavigatorMoveNextItem;
            this.bindingNavigator1.MovePreviousItem = this.bindingNavigatorMovePreviousItem;
            this.bindingNavigator1.Name = "bindingNavigator1";
            this.bindingNavigator1.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.bindingNavigator1.PositionItem = this.bindingNavigatorPositionItem;
            this.bindingNavigator1.Size = new System.Drawing.Size(806, 25);
            this.bindingNavigator1.TabIndex = 0;
            this.bindingNavigator1.Text = "bindingNavigator1";
            // 
            // bindingNavigatorCountItem
            // 
            this.bindingNavigatorCountItem.Name = "bindingNavigatorCountItem";
            this.bindingNavigatorCountItem.Size = new System.Drawing.Size(35, 22);
            this.bindingNavigatorCountItem.Text = "of {0}";
            this.bindingNavigatorCountItem.ToolTipText = "Total number of items";
            // 
            // bindingNavigatorDeleteItem
            // 
            this.bindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorDeleteItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorDeleteItem.Image")));
            this.bindingNavigatorDeleteItem.Name = "bindingNavigatorDeleteItem";
            this.bindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorDeleteItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorDeleteItem.Text = "Delete";
            // 
            // bindingNavigatorMoveFirstItem
            // 
            this.bindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveFirstItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveFirstItem.Image")));
            this.bindingNavigatorMoveFirstItem.Name = "bindingNavigatorMoveFirstItem";
            this.bindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveFirstItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveFirstItem.Text = "Move first";
            // 
            // bindingNavigatorMovePreviousItem
            // 
            this.bindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMovePreviousItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMovePreviousItem.Image")));
            this.bindingNavigatorMovePreviousItem.Name = "bindingNavigatorMovePreviousItem";
            this.bindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMovePreviousItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMovePreviousItem.Text = "Move previous";
            // 
            // bindingNavigatorSeparator
            // 
            this.bindingNavigatorSeparator.Name = "bindingNavigatorSeparator";
            this.bindingNavigatorSeparator.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorPositionItem
            // 
            this.bindingNavigatorPositionItem.AccessibleName = "Position";
            this.bindingNavigatorPositionItem.AutoSize = false;
            this.bindingNavigatorPositionItem.Name = "bindingNavigatorPositionItem";
            this.bindingNavigatorPositionItem.Size = new System.Drawing.Size(50, 23);
            this.bindingNavigatorPositionItem.Text = "0";
            this.bindingNavigatorPositionItem.ToolTipText = "Current position";
            // 
            // bindingNavigatorSeparator1
            // 
            this.bindingNavigatorSeparator1.Name = "bindingNavigatorSeparator1";
            this.bindingNavigatorSeparator1.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorMoveNextItem
            // 
            this.bindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveNextItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveNextItem.Image")));
            this.bindingNavigatorMoveNextItem.Name = "bindingNavigatorMoveNextItem";
            this.bindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveNextItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveNextItem.Text = "Move next";
            // 
            // bindingNavigatorMoveLastItem
            // 
            this.bindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveLastItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveLastItem.Image")));
            this.bindingNavigatorMoveLastItem.Name = "bindingNavigatorMoveLastItem";
            this.bindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveLastItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveLastItem.Text = "Move last";
            // 
            // bindingNavigatorSeparator2
            // 
            this.bindingNavigatorSeparator2.Name = "bindingNavigatorSeparator2";
            this.bindingNavigatorSeparator2.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorAddNewItem
            // 
            this.bindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorAddNewItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorAddNewItem.Image")));
            this.bindingNavigatorAddNewItem.Name = "bindingNavigatorAddNewItem";
            this.bindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorAddNewItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorAddNewItem.Text = "Add new";
            this.bindingNavigatorAddNewItem.Click += new System.EventHandler(this.bindingNavigatorAddNewItem_Click);
            // 
            // toolStripButton1
            // 
            this.toolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButton1.Image")));
            this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButton1.Name = "toolStripButton1";
            this.toolStripButton1.Size = new System.Drawing.Size(23, 22);
            this.toolStripButton1.Text = "Save";
            this.toolStripButton1.Click += new System.EventHandler(this.Save_Click);
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // Panel1
            // 
            this.Panel1.AutoScroll = true;
            this.Panel1.AutoSize = true;
            this.Panel1.Controls.Add(this.order_idLabel);
            this.Panel1.Controls.Add(this.order_idTextBox);
            this.Panel1.Controls.Add(this.invoice_noLabel);
            this.Panel1.Controls.Add(this.invoice_noTextBox);
            this.Panel1.Controls.Add(this.invoice_prefixLabel);
            this.Panel1.Controls.Add(this.invoice_prefixTextBox);
            this.Panel1.Controls.Add(this.store_idLabel);
            this.Panel1.Controls.Add(this.store_idTextBox);
            this.Panel1.Controls.Add(this.store_nameLabel);
            this.Panel1.Controls.Add(this.store_nameTextBox);
            this.Panel1.Controls.Add(this.store_urlLabel);
            this.Panel1.Controls.Add(this.store_urlTextBox);
            this.Panel1.Controls.Add(this.customer_idLabel);
            this.Panel1.Controls.Add(this.customer_idTextBox);
            this.Panel1.Controls.Add(this.customer_group_idLabel);
            this.Panel1.Controls.Add(this.customer_group_idTextBox);
            this.Panel1.Controls.Add(this.firstnameLabel);
            this.Panel1.Controls.Add(this.firstnameTextBox);
            this.Panel1.Controls.Add(this.lastnameLabel);
            this.Panel1.Controls.Add(this.lastnameTextBox);
            this.Panel1.Controls.Add(this.emailLabel);
            this.Panel1.Controls.Add(this.emailTextBox);
            this.Panel1.Controls.Add(this.telephoneLabel);
            this.Panel1.Controls.Add(this.telephoneTextBox);
            this.Panel1.Controls.Add(this.faxLabel);
            this.Panel1.Controls.Add(this.faxTextBox);
            this.Panel1.Controls.Add(this.payment_firstnameLabel);
            this.Panel1.Controls.Add(this.payment_firstnameTextBox);
            this.Panel1.Controls.Add(this.payment_lastnameLabel);
            this.Panel1.Controls.Add(this.payment_lastnameTextBox);
            this.Panel1.Controls.Add(this.payment_companyLabel);
            this.Panel1.Controls.Add(this.payment_companyTextBox);
            this.Panel1.Controls.Add(this.payment_company_idLabel);
            this.Panel1.Controls.Add(this.payment_company_idTextBox);
            this.Panel1.Controls.Add(this.payment_tax_idLabel);
            this.Panel1.Controls.Add(this.payment_tax_idTextBox);
            this.Panel1.Controls.Add(this.payment_address_1Label);
            this.Panel1.Controls.Add(this.payment_address_1TextBox);
            this.Panel1.Controls.Add(this.payment_address_2Label);
            this.Panel1.Controls.Add(this.payment_address_2TextBox);
            this.Panel1.Controls.Add(this.payment_cityLabel);
            this.Panel1.Controls.Add(this.payment_cityTextBox);
            this.Panel1.Controls.Add(this.payment_postcodeLabel);
            this.Panel1.Controls.Add(this.payment_postcodeTextBox);
            this.Panel1.Controls.Add(this.payment_countryLabel);
            this.Panel1.Controls.Add(this.payment_countryTextBox);
            this.Panel1.Controls.Add(this.payment_country_idLabel);
            this.Panel1.Controls.Add(this.payment_country_idTextBox);
            this.Panel1.Controls.Add(this.payment_zoneLabel);
            this.Panel1.Controls.Add(this.payment_zoneTextBox);
            this.Panel1.Controls.Add(this.payment_zone_idLabel);
            this.Panel1.Controls.Add(this.payment_zone_idTextBox);
            this.Panel1.Controls.Add(this.payment_address_formatLabel);
            this.Panel1.Controls.Add(this.payment_address_formatTextBox);
            this.Panel1.Controls.Add(this.payment_methodLabel);
            this.Panel1.Controls.Add(this.payment_methodTextBox);
            this.Panel1.Controls.Add(this.payment_codeLabel);
            this.Panel1.Controls.Add(this.payment_codeTextBox);
            this.Panel1.Controls.Add(this.shipping_firstnameLabel);
            this.Panel1.Controls.Add(this.shipping_firstnameTextBox);
            this.Panel1.Controls.Add(this.shipping_lastnameLabel);
            this.Panel1.Controls.Add(this.shipping_lastnameTextBox);
            this.Panel1.Controls.Add(this.shipping_companyLabel);
            this.Panel1.Controls.Add(this.shipping_companyTextBox);
            this.Panel1.Controls.Add(this.shipping_address_1Label);
            this.Panel1.Controls.Add(this.shipping_address_1TextBox);
            this.Panel1.Controls.Add(this.shipping_address_2Label);
            this.Panel1.Controls.Add(this.shipping_address_2TextBox);
            this.Panel1.Controls.Add(this.shipping_cityLabel);
            this.Panel1.Controls.Add(this.shipping_cityTextBox);
            this.Panel1.Controls.Add(this.shipping_postcodeLabel);
            this.Panel1.Controls.Add(this.shipping_postcodeTextBox);
            this.Panel1.Controls.Add(this.shipping_countryLabel);
            this.Panel1.Controls.Add(this.shipping_countryTextBox);
            this.Panel1.Controls.Add(this.shipping_country_idLabel);
            this.Panel1.Controls.Add(this.shipping_country_idTextBox);
            this.Panel1.Controls.Add(this.shipping_zoneLabel);
            this.Panel1.Controls.Add(this.shipping_zoneTextBox);
            this.Panel1.Controls.Add(this.shipping_zone_idLabel);
            this.Panel1.Controls.Add(this.shipping_zone_idTextBox);
            this.Panel1.Controls.Add(this.shipping_address_formatLabel);
            this.Panel1.Controls.Add(this.shipping_address_formatTextBox);
            this.Panel1.Controls.Add(this.shipping_methodLabel);
            this.Panel1.Controls.Add(this.shipping_methodTextBox);
            this.Panel1.Controls.Add(this.shipping_codeLabel);
            this.Panel1.Controls.Add(this.shipping_codeTextBox);
            this.Panel1.Controls.Add(this.commentLabel);
            this.Panel1.Controls.Add(this.commentTextBox);
            this.Panel1.Controls.Add(this.totalLabel);
            this.Panel1.Controls.Add(this.totalTextBox);
            this.Panel1.Controls.Add(this.order_status_idLabel);
            this.Panel1.Controls.Add(this.order_status_idTextBox);
            this.Panel1.Controls.Add(this.affiliate_idLabel);
            this.Panel1.Controls.Add(this.affiliate_idTextBox);
            this.Panel1.Controls.Add(this.commissionLabel);
            this.Panel1.Controls.Add(this.commissionTextBox);
            this.Panel1.Controls.Add(this.language_idLabel);
            this.Panel1.Controls.Add(this.language_idTextBox);
            this.Panel1.Controls.Add(this.currency_idLabel);
            this.Panel1.Controls.Add(this.currency_idTextBox);
            this.Panel1.Controls.Add(this.currency_codeLabel);
            this.Panel1.Controls.Add(this.currency_codeTextBox);
            this.Panel1.Controls.Add(this.currency_valueLabel);
            this.Panel1.Controls.Add(this.currency_valueTextBox);
            this.Panel1.Controls.Add(this.ipLabel);
            this.Panel1.Controls.Add(this.ipTextBox);
            this.Panel1.Controls.Add(this.forwarded_ipLabel);
            this.Panel1.Controls.Add(this.forwarded_ipTextBox);
            this.Panel1.Controls.Add(this.user_agentLabel);
            this.Panel1.Controls.Add(this.user_agentTextBox);
            this.Panel1.Controls.Add(this.accept_languageLabel);
            this.Panel1.Controls.Add(this.accept_languageTextBox);
            this.Panel1.Controls.Add(this.date_addedLabel);
            this.Panel1.Controls.Add(this.date_added_dateTimePicker);
            this.Panel1.Controls.Add(this.date_modifiedLabel);
            this.Panel1.Controls.Add(this.date_modified_dateTimePicker);
            this.Panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Panel1.Location = new System.Drawing.Point(10, 0);
            this.Panel1.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
            this.Panel1.Name = "Panel1";
            this.Panel1.Size = new System.Drawing.Size(786, 484);
            this.Panel1.TabIndex = 1;
            // 
            // order_idLabel
            // 
            this.order_idLabel.AutoSize = true;
            this.order_idLabel.Location = new System.Drawing.Point(129, 50);
            this.order_idLabel.Name = "order_idLabel";
            this.order_idLabel.Size = new System.Drawing.Size(45, 13);
            this.order_idLabel.TabIndex = 1;
            this.order_idLabel.Text = "order_id";
            // 
            // order_idTextBox
            // 
            this.order_idTextBox.Location = new System.Drawing.Point(184, 50);
            this.order_idTextBox.Name = "order_idTextBox";
            this.order_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.order_idTextBox.TabIndex = 2;
            this.order_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.order_idTextBox_Validating);
            // 
            // invoice_noLabel
            // 
            this.invoice_noLabel.AutoSize = true;
            this.invoice_noLabel.Location = new System.Drawing.Point(115, 76);
            this.invoice_noLabel.Name = "invoice_noLabel";
            this.invoice_noLabel.Size = new System.Drawing.Size(59, 13);
            this.invoice_noLabel.TabIndex = 3;
            this.invoice_noLabel.Text = "invoice_no";
            // 
            // invoice_noTextBox
            // 
            this.invoice_noTextBox.Location = new System.Drawing.Point(184, 76);
            this.invoice_noTextBox.Name = "invoice_noTextBox";
            this.invoice_noTextBox.Size = new System.Drawing.Size(100, 20);
            this.invoice_noTextBox.TabIndex = 4;
            this.invoice_noTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.invoice_noTextBox_Validating);
            // 
            // invoice_prefixLabel
            // 
            this.invoice_prefixLabel.AutoSize = true;
            this.invoice_prefixLabel.Location = new System.Drawing.Point(102, 102);
            this.invoice_prefixLabel.Name = "invoice_prefixLabel";
            this.invoice_prefixLabel.Size = new System.Drawing.Size(72, 13);
            this.invoice_prefixLabel.TabIndex = 5;
            this.invoice_prefixLabel.Text = "invoice_prefix";
            // 
            // invoice_prefixTextBox
            // 
            this.invoice_prefixTextBox.Location = new System.Drawing.Point(184, 102);
            this.invoice_prefixTextBox.Name = "invoice_prefixTextBox";
            this.invoice_prefixTextBox.Size = new System.Drawing.Size(100, 20);
            this.invoice_prefixTextBox.TabIndex = 6;
            this.invoice_prefixTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.invoice_prefixTextBox_Validating);
            // 
            // store_idLabel
            // 
            this.store_idLabel.AutoSize = true;
            this.store_idLabel.Location = new System.Drawing.Point(130, 128);
            this.store_idLabel.Name = "store_idLabel";
            this.store_idLabel.Size = new System.Drawing.Size(44, 13);
            this.store_idLabel.TabIndex = 7;
            this.store_idLabel.Text = "store_id";
            // 
            // store_idTextBox
            // 
            this.store_idTextBox.Location = new System.Drawing.Point(184, 128);
            this.store_idTextBox.Name = "store_idTextBox";
            this.store_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.store_idTextBox.TabIndex = 8;
            this.store_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.store_idTextBox_Validating);
            // 
            // store_nameLabel
            // 
            this.store_nameLabel.AutoSize = true;
            this.store_nameLabel.Location = new System.Drawing.Point(112, 154);
            this.store_nameLabel.Name = "store_nameLabel";
            this.store_nameLabel.Size = new System.Drawing.Size(62, 13);
            this.store_nameLabel.TabIndex = 9;
            this.store_nameLabel.Text = "store_name";
            // 
            // store_nameTextBox
            // 
            this.store_nameTextBox.Location = new System.Drawing.Point(184, 154);
            this.store_nameTextBox.Name = "store_nameTextBox";
            this.store_nameTextBox.Size = new System.Drawing.Size(100, 20);
            this.store_nameTextBox.TabIndex = 10;
            this.store_nameTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.store_nameTextBox_Validating);
            // 
            // store_urlLabel
            // 
            this.store_urlLabel.AutoSize = true;
            this.store_urlLabel.Location = new System.Drawing.Point(127, 180);
            this.store_urlLabel.Name = "store_urlLabel";
            this.store_urlLabel.Size = new System.Drawing.Size(47, 13);
            this.store_urlLabel.TabIndex = 11;
            this.store_urlLabel.Text = "store_url";
            // 
            // store_urlTextBox
            // 
            this.store_urlTextBox.Location = new System.Drawing.Point(184, 180);
            this.store_urlTextBox.Name = "store_urlTextBox";
            this.store_urlTextBox.Size = new System.Drawing.Size(100, 20);
            this.store_urlTextBox.TabIndex = 12;
            this.store_urlTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.store_urlTextBox_Validating);
            // 
            // customer_idLabel
            // 
            this.customer_idLabel.AutoSize = true;
            this.customer_idLabel.Location = new System.Drawing.Point(110, 206);
            this.customer_idLabel.Name = "customer_idLabel";
            this.customer_idLabel.Size = new System.Drawing.Size(64, 13);
            this.customer_idLabel.TabIndex = 13;
            this.customer_idLabel.Text = "customer_id";
            // 
            // customer_idTextBox
            // 
            this.customer_idTextBox.Location = new System.Drawing.Point(184, 206);
            this.customer_idTextBox.Name = "customer_idTextBox";
            this.customer_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.customer_idTextBox.TabIndex = 14;
            this.customer_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.customer_idTextBox_Validating);
            // 
            // customer_group_idLabel
            // 
            this.customer_group_idLabel.AutoSize = true;
            this.customer_group_idLabel.Location = new System.Drawing.Point(77, 232);
            this.customer_group_idLabel.Name = "customer_group_idLabel";
            this.customer_group_idLabel.Size = new System.Drawing.Size(97, 13);
            this.customer_group_idLabel.TabIndex = 15;
            this.customer_group_idLabel.Text = "customer_group_id";
            // 
            // customer_group_idTextBox
            // 
            this.customer_group_idTextBox.Location = new System.Drawing.Point(184, 232);
            this.customer_group_idTextBox.Name = "customer_group_idTextBox";
            this.customer_group_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.customer_group_idTextBox.TabIndex = 16;
            this.customer_group_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.customer_group_idTextBox_Validating);
            // 
            // firstnameLabel
            // 
            this.firstnameLabel.AutoSize = true;
            this.firstnameLabel.Location = new System.Drawing.Point(125, 258);
            this.firstnameLabel.Name = "firstnameLabel";
            this.firstnameLabel.Size = new System.Drawing.Size(49, 13);
            this.firstnameLabel.TabIndex = 17;
            this.firstnameLabel.Text = "firstname";
            // 
            // firstnameTextBox
            // 
            this.firstnameTextBox.Location = new System.Drawing.Point(184, 258);
            this.firstnameTextBox.Name = "firstnameTextBox";
            this.firstnameTextBox.Size = new System.Drawing.Size(100, 20);
            this.firstnameTextBox.TabIndex = 18;
            this.firstnameTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.firstnameTextBox_Validating);
            // 
            // lastnameLabel
            // 
            this.lastnameLabel.AutoSize = true;
            this.lastnameLabel.Location = new System.Drawing.Point(125, 284);
            this.lastnameLabel.Name = "lastnameLabel";
            this.lastnameLabel.Size = new System.Drawing.Size(49, 13);
            this.lastnameLabel.TabIndex = 19;
            this.lastnameLabel.Text = "lastname";
            // 
            // lastnameTextBox
            // 
            this.lastnameTextBox.Location = new System.Drawing.Point(184, 284);
            this.lastnameTextBox.Name = "lastnameTextBox";
            this.lastnameTextBox.Size = new System.Drawing.Size(100, 20);
            this.lastnameTextBox.TabIndex = 20;
            this.lastnameTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.lastnameTextBox_Validating);
            // 
            // emailLabel
            // 
            this.emailLabel.AutoSize = true;
            this.emailLabel.Location = new System.Drawing.Point(143, 310);
            this.emailLabel.Name = "emailLabel";
            this.emailLabel.Size = new System.Drawing.Size(31, 13);
            this.emailLabel.TabIndex = 21;
            this.emailLabel.Text = "email";
            // 
            // emailTextBox
            // 
            this.emailTextBox.Location = new System.Drawing.Point(184, 310);
            this.emailTextBox.Name = "emailTextBox";
            this.emailTextBox.Size = new System.Drawing.Size(100, 20);
            this.emailTextBox.TabIndex = 22;
            this.emailTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.emailTextBox_Validating);
            // 
            // telephoneLabel
            // 
            this.telephoneLabel.AutoSize = true;
            this.telephoneLabel.Location = new System.Drawing.Point(120, 336);
            this.telephoneLabel.Name = "telephoneLabel";
            this.telephoneLabel.Size = new System.Drawing.Size(54, 13);
            this.telephoneLabel.TabIndex = 23;
            this.telephoneLabel.Text = "telephone";
            // 
            // telephoneTextBox
            // 
            this.telephoneTextBox.Location = new System.Drawing.Point(184, 336);
            this.telephoneTextBox.Name = "telephoneTextBox";
            this.telephoneTextBox.Size = new System.Drawing.Size(100, 20);
            this.telephoneTextBox.TabIndex = 24;
            this.telephoneTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.telephoneTextBox_Validating);
            // 
            // faxLabel
            // 
            this.faxLabel.AutoSize = true;
            this.faxLabel.Location = new System.Drawing.Point(153, 362);
            this.faxLabel.Name = "faxLabel";
            this.faxLabel.Size = new System.Drawing.Size(21, 13);
            this.faxLabel.TabIndex = 25;
            this.faxLabel.Text = "fax";
            // 
            // faxTextBox
            // 
            this.faxTextBox.Location = new System.Drawing.Point(184, 362);
            this.faxTextBox.Name = "faxTextBox";
            this.faxTextBox.Size = new System.Drawing.Size(100, 20);
            this.faxTextBox.TabIndex = 26;
            this.faxTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.faxTextBox_Validating);
            // 
            // payment_firstnameLabel
            // 
            this.payment_firstnameLabel.AutoSize = true;
            this.payment_firstnameLabel.Location = new System.Drawing.Point(79, 388);
            this.payment_firstnameLabel.Name = "payment_firstnameLabel";
            this.payment_firstnameLabel.Size = new System.Drawing.Size(95, 13);
            this.payment_firstnameLabel.TabIndex = 27;
            this.payment_firstnameLabel.Text = "payment_firstname";
            // 
            // payment_firstnameTextBox
            // 
            this.payment_firstnameTextBox.Location = new System.Drawing.Point(184, 388);
            this.payment_firstnameTextBox.Name = "payment_firstnameTextBox";
            this.payment_firstnameTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_firstnameTextBox.TabIndex = 28;
            this.payment_firstnameTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_firstnameTextBox_Validating);
            // 
            // payment_lastnameLabel
            // 
            this.payment_lastnameLabel.AutoSize = true;
            this.payment_lastnameLabel.Location = new System.Drawing.Point(79, 414);
            this.payment_lastnameLabel.Name = "payment_lastnameLabel";
            this.payment_lastnameLabel.Size = new System.Drawing.Size(95, 13);
            this.payment_lastnameLabel.TabIndex = 29;
            this.payment_lastnameLabel.Text = "payment_lastname";
            // 
            // payment_lastnameTextBox
            // 
            this.payment_lastnameTextBox.Location = new System.Drawing.Point(184, 414);
            this.payment_lastnameTextBox.Name = "payment_lastnameTextBox";
            this.payment_lastnameTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_lastnameTextBox.TabIndex = 30;
            this.payment_lastnameTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_lastnameTextBox_Validating);
            // 
            // payment_companyLabel
            // 
            this.payment_companyLabel.AutoSize = true;
            this.payment_companyLabel.Location = new System.Drawing.Point(78, 440);
            this.payment_companyLabel.Name = "payment_companyLabel";
            this.payment_companyLabel.Size = new System.Drawing.Size(96, 13);
            this.payment_companyLabel.TabIndex = 31;
            this.payment_companyLabel.Text = "payment_company";
            // 
            // payment_companyTextBox
            // 
            this.payment_companyTextBox.Location = new System.Drawing.Point(184, 440);
            this.payment_companyTextBox.Name = "payment_companyTextBox";
            this.payment_companyTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_companyTextBox.TabIndex = 32;
            this.payment_companyTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_companyTextBox_Validating);
            // 
            // payment_company_idLabel
            // 
            this.payment_company_idLabel.AutoSize = true;
            this.payment_company_idLabel.Location = new System.Drawing.Point(64, 466);
            this.payment_company_idLabel.Name = "payment_company_idLabel";
            this.payment_company_idLabel.Size = new System.Drawing.Size(110, 13);
            this.payment_company_idLabel.TabIndex = 33;
            this.payment_company_idLabel.Text = "payment_company_id";
            // 
            // payment_company_idTextBox
            // 
            this.payment_company_idTextBox.Location = new System.Drawing.Point(184, 466);
            this.payment_company_idTextBox.Name = "payment_company_idTextBox";
            this.payment_company_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_company_idTextBox.TabIndex = 34;
            this.payment_company_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_company_idTextBox_Validating);
            // 
            // payment_tax_idLabel
            // 
            this.payment_tax_idLabel.AutoSize = true;
            this.payment_tax_idLabel.Location = new System.Drawing.Point(93, 492);
            this.payment_tax_idLabel.Name = "payment_tax_idLabel";
            this.payment_tax_idLabel.Size = new System.Drawing.Size(81, 13);
            this.payment_tax_idLabel.TabIndex = 35;
            this.payment_tax_idLabel.Text = "payment_tax_id";
            // 
            // payment_tax_idTextBox
            // 
            this.payment_tax_idTextBox.Location = new System.Drawing.Point(184, 492);
            this.payment_tax_idTextBox.Name = "payment_tax_idTextBox";
            this.payment_tax_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_tax_idTextBox.TabIndex = 36;
            this.payment_tax_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_tax_idTextBox_Validating);
            // 
            // payment_address_1Label
            // 
            this.payment_address_1Label.AutoSize = true;
            this.payment_address_1Label.Location = new System.Drawing.Point(72, 518);
            this.payment_address_1Label.Name = "payment_address_1Label";
            this.payment_address_1Label.Size = new System.Drawing.Size(102, 13);
            this.payment_address_1Label.TabIndex = 37;
            this.payment_address_1Label.Text = "payment_address_1";
            // 
            // payment_address_1TextBox
            // 
            this.payment_address_1TextBox.Location = new System.Drawing.Point(184, 518);
            this.payment_address_1TextBox.Name = "payment_address_1TextBox";
            this.payment_address_1TextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_address_1TextBox.TabIndex = 38;
            this.payment_address_1TextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_address_1TextBox_Validating);
            // 
            // payment_address_2Label
            // 
            this.payment_address_2Label.AutoSize = true;
            this.payment_address_2Label.Location = new System.Drawing.Point(72, 544);
            this.payment_address_2Label.Name = "payment_address_2Label";
            this.payment_address_2Label.Size = new System.Drawing.Size(102, 13);
            this.payment_address_2Label.TabIndex = 39;
            this.payment_address_2Label.Text = "payment_address_2";
            // 
            // payment_address_2TextBox
            // 
            this.payment_address_2TextBox.Location = new System.Drawing.Point(184, 544);
            this.payment_address_2TextBox.Name = "payment_address_2TextBox";
            this.payment_address_2TextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_address_2TextBox.TabIndex = 40;
            this.payment_address_2TextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_address_2TextBox_Validating);
            // 
            // payment_cityLabel
            // 
            this.payment_cityLabel.AutoSize = true;
            this.payment_cityLabel.Location = new System.Drawing.Point(105, 570);
            this.payment_cityLabel.Name = "payment_cityLabel";
            this.payment_cityLabel.Size = new System.Drawing.Size(69, 13);
            this.payment_cityLabel.TabIndex = 41;
            this.payment_cityLabel.Text = "payment_city";
            // 
            // payment_cityTextBox
            // 
            this.payment_cityTextBox.Location = new System.Drawing.Point(184, 570);
            this.payment_cityTextBox.Name = "payment_cityTextBox";
            this.payment_cityTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_cityTextBox.TabIndex = 42;
            this.payment_cityTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_cityTextBox_Validating);
            // 
            // payment_postcodeLabel
            // 
            this.payment_postcodeLabel.AutoSize = true;
            this.payment_postcodeLabel.Location = new System.Drawing.Point(77, 596);
            this.payment_postcodeLabel.Name = "payment_postcodeLabel";
            this.payment_postcodeLabel.Size = new System.Drawing.Size(97, 13);
            this.payment_postcodeLabel.TabIndex = 43;
            this.payment_postcodeLabel.Text = "payment_postcode";
            // 
            // payment_postcodeTextBox
            // 
            this.payment_postcodeTextBox.Location = new System.Drawing.Point(184, 596);
            this.payment_postcodeTextBox.Name = "payment_postcodeTextBox";
            this.payment_postcodeTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_postcodeTextBox.TabIndex = 44;
            this.payment_postcodeTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_postcodeTextBox_Validating);
            // 
            // payment_countryLabel
            // 
            this.payment_countryLabel.AutoSize = true;
            this.payment_countryLabel.Location = new System.Drawing.Point(86, 622);
            this.payment_countryLabel.Name = "payment_countryLabel";
            this.payment_countryLabel.Size = new System.Drawing.Size(88, 13);
            this.payment_countryLabel.TabIndex = 45;
            this.payment_countryLabel.Text = "payment_country";
            // 
            // payment_countryTextBox
            // 
            this.payment_countryTextBox.Location = new System.Drawing.Point(184, 622);
            this.payment_countryTextBox.Name = "payment_countryTextBox";
            this.payment_countryTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_countryTextBox.TabIndex = 46;
            this.payment_countryTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_countryTextBox_Validating);
            // 
            // payment_country_idLabel
            // 
            this.payment_country_idLabel.AutoSize = true;
            this.payment_country_idLabel.Location = new System.Drawing.Point(72, 648);
            this.payment_country_idLabel.Name = "payment_country_idLabel";
            this.payment_country_idLabel.Size = new System.Drawing.Size(102, 13);
            this.payment_country_idLabel.TabIndex = 47;
            this.payment_country_idLabel.Text = "payment_country_id";
            // 
            // payment_country_idTextBox
            // 
            this.payment_country_idTextBox.Location = new System.Drawing.Point(184, 648);
            this.payment_country_idTextBox.Name = "payment_country_idTextBox";
            this.payment_country_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_country_idTextBox.TabIndex = 48;
            this.payment_country_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_country_idTextBox_Validating);
            // 
            // payment_zoneLabel
            // 
            this.payment_zoneLabel.AutoSize = true;
            this.payment_zoneLabel.Location = new System.Drawing.Point(98, 674);
            this.payment_zoneLabel.Name = "payment_zoneLabel";
            this.payment_zoneLabel.Size = new System.Drawing.Size(76, 13);
            this.payment_zoneLabel.TabIndex = 49;
            this.payment_zoneLabel.Text = "payment_zone";
            // 
            // payment_zoneTextBox
            // 
            this.payment_zoneTextBox.Location = new System.Drawing.Point(184, 674);
            this.payment_zoneTextBox.Name = "payment_zoneTextBox";
            this.payment_zoneTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_zoneTextBox.TabIndex = 50;
            this.payment_zoneTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_zoneTextBox_Validating);
            // 
            // payment_zone_idLabel
            // 
            this.payment_zone_idLabel.AutoSize = true;
            this.payment_zone_idLabel.Location = new System.Drawing.Point(84, 700);
            this.payment_zone_idLabel.Name = "payment_zone_idLabel";
            this.payment_zone_idLabel.Size = new System.Drawing.Size(90, 13);
            this.payment_zone_idLabel.TabIndex = 51;
            this.payment_zone_idLabel.Text = "payment_zone_id";
            // 
            // payment_zone_idTextBox
            // 
            this.payment_zone_idTextBox.Location = new System.Drawing.Point(184, 700);
            this.payment_zone_idTextBox.Name = "payment_zone_idTextBox";
            this.payment_zone_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_zone_idTextBox.TabIndex = 52;
            this.payment_zone_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_zone_idTextBox_Validating);
            // 
            // payment_address_formatLabel
            // 
            this.payment_address_formatLabel.AutoSize = true;
            this.payment_address_formatLabel.Location = new System.Drawing.Point(49, 726);
            this.payment_address_formatLabel.Name = "payment_address_formatLabel";
            this.payment_address_formatLabel.Size = new System.Drawing.Size(125, 13);
            this.payment_address_formatLabel.TabIndex = 53;
            this.payment_address_formatLabel.Text = "payment_address_format";
            // 
            // payment_address_formatTextBox
            // 
            this.payment_address_formatTextBox.Location = new System.Drawing.Point(184, 726);
            this.payment_address_formatTextBox.Name = "payment_address_formatTextBox";
            this.payment_address_formatTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_address_formatTextBox.TabIndex = 54;
            this.payment_address_formatTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_address_formatTextBox_Validating);
            // 
            // payment_methodLabel
            // 
            this.payment_methodLabel.AutoSize = true;
            this.payment_methodLabel.Location = new System.Drawing.Point(86, 752);
            this.payment_methodLabel.Name = "payment_methodLabel";
            this.payment_methodLabel.Size = new System.Drawing.Size(88, 13);
            this.payment_methodLabel.TabIndex = 55;
            this.payment_methodLabel.Text = "payment_method";
            // 
            // payment_methodTextBox
            // 
            this.payment_methodTextBox.Location = new System.Drawing.Point(184, 752);
            this.payment_methodTextBox.Name = "payment_methodTextBox";
            this.payment_methodTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_methodTextBox.TabIndex = 56;
            this.payment_methodTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_methodTextBox_Validating);
            // 
            // payment_codeLabel
            // 
            this.payment_codeLabel.AutoSize = true;
            this.payment_codeLabel.Location = new System.Drawing.Point(97, 778);
            this.payment_codeLabel.Name = "payment_codeLabel";
            this.payment_codeLabel.Size = new System.Drawing.Size(77, 13);
            this.payment_codeLabel.TabIndex = 57;
            this.payment_codeLabel.Text = "payment_code";
            // 
            // payment_codeTextBox
            // 
            this.payment_codeTextBox.Location = new System.Drawing.Point(184, 778);
            this.payment_codeTextBox.Name = "payment_codeTextBox";
            this.payment_codeTextBox.Size = new System.Drawing.Size(100, 20);
            this.payment_codeTextBox.TabIndex = 58;
            this.payment_codeTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.payment_codeTextBox_Validating);
            // 
            // shipping_firstnameLabel
            // 
            this.shipping_firstnameLabel.AutoSize = true;
            this.shipping_firstnameLabel.Location = new System.Drawing.Point(424, 50);
            this.shipping_firstnameLabel.Name = "shipping_firstnameLabel";
            this.shipping_firstnameLabel.Size = new System.Drawing.Size(94, 13);
            this.shipping_firstnameLabel.TabIndex = 59;
            this.shipping_firstnameLabel.Text = "shipping_firstname";
            // 
            // shipping_firstnameTextBox
            // 
            this.shipping_firstnameTextBox.Location = new System.Drawing.Point(528, 50);
            this.shipping_firstnameTextBox.Name = "shipping_firstnameTextBox";
            this.shipping_firstnameTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_firstnameTextBox.TabIndex = 60;
            this.shipping_firstnameTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_firstnameTextBox_Validating);
            // 
            // shipping_lastnameLabel
            // 
            this.shipping_lastnameLabel.AutoSize = true;
            this.shipping_lastnameLabel.Location = new System.Drawing.Point(424, 76);
            this.shipping_lastnameLabel.Name = "shipping_lastnameLabel";
            this.shipping_lastnameLabel.Size = new System.Drawing.Size(94, 13);
            this.shipping_lastnameLabel.TabIndex = 61;
            this.shipping_lastnameLabel.Text = "shipping_lastname";
            // 
            // shipping_lastnameTextBox
            // 
            this.shipping_lastnameTextBox.Location = new System.Drawing.Point(528, 76);
            this.shipping_lastnameTextBox.Name = "shipping_lastnameTextBox";
            this.shipping_lastnameTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_lastnameTextBox.TabIndex = 62;
            this.shipping_lastnameTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_lastnameTextBox_Validating);
            // 
            // shipping_companyLabel
            // 
            this.shipping_companyLabel.AutoSize = true;
            this.shipping_companyLabel.Location = new System.Drawing.Point(423, 102);
            this.shipping_companyLabel.Name = "shipping_companyLabel";
            this.shipping_companyLabel.Size = new System.Drawing.Size(95, 13);
            this.shipping_companyLabel.TabIndex = 63;
            this.shipping_companyLabel.Text = "shipping_company";
            // 
            // shipping_companyTextBox
            // 
            this.shipping_companyTextBox.Location = new System.Drawing.Point(528, 102);
            this.shipping_companyTextBox.Name = "shipping_companyTextBox";
            this.shipping_companyTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_companyTextBox.TabIndex = 64;
            this.shipping_companyTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_companyTextBox_Validating);
            // 
            // shipping_address_1Label
            // 
            this.shipping_address_1Label.AutoSize = true;
            this.shipping_address_1Label.Location = new System.Drawing.Point(417, 128);
            this.shipping_address_1Label.Name = "shipping_address_1Label";
            this.shipping_address_1Label.Size = new System.Drawing.Size(101, 13);
            this.shipping_address_1Label.TabIndex = 65;
            this.shipping_address_1Label.Text = "shipping_address_1";
            // 
            // shipping_address_1TextBox
            // 
            this.shipping_address_1TextBox.Location = new System.Drawing.Point(528, 128);
            this.shipping_address_1TextBox.Name = "shipping_address_1TextBox";
            this.shipping_address_1TextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_address_1TextBox.TabIndex = 66;
            this.shipping_address_1TextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_address_1TextBox_Validating);
            // 
            // shipping_address_2Label
            // 
            this.shipping_address_2Label.AutoSize = true;
            this.shipping_address_2Label.Location = new System.Drawing.Point(417, 154);
            this.shipping_address_2Label.Name = "shipping_address_2Label";
            this.shipping_address_2Label.Size = new System.Drawing.Size(101, 13);
            this.shipping_address_2Label.TabIndex = 67;
            this.shipping_address_2Label.Text = "shipping_address_2";
            // 
            // shipping_address_2TextBox
            // 
            this.shipping_address_2TextBox.Location = new System.Drawing.Point(528, 154);
            this.shipping_address_2TextBox.Name = "shipping_address_2TextBox";
            this.shipping_address_2TextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_address_2TextBox.TabIndex = 68;
            this.shipping_address_2TextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_address_2TextBox_Validating);
            // 
            // shipping_cityLabel
            // 
            this.shipping_cityLabel.AutoSize = true;
            this.shipping_cityLabel.Location = new System.Drawing.Point(450, 180);
            this.shipping_cityLabel.Name = "shipping_cityLabel";
            this.shipping_cityLabel.Size = new System.Drawing.Size(68, 13);
            this.shipping_cityLabel.TabIndex = 69;
            this.shipping_cityLabel.Text = "shipping_city";
            // 
            // shipping_cityTextBox
            // 
            this.shipping_cityTextBox.Location = new System.Drawing.Point(528, 180);
            this.shipping_cityTextBox.Name = "shipping_cityTextBox";
            this.shipping_cityTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_cityTextBox.TabIndex = 70;
            this.shipping_cityTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_cityTextBox_Validating);
            // 
            // shipping_postcodeLabel
            // 
            this.shipping_postcodeLabel.AutoSize = true;
            this.shipping_postcodeLabel.Location = new System.Drawing.Point(422, 206);
            this.shipping_postcodeLabel.Name = "shipping_postcodeLabel";
            this.shipping_postcodeLabel.Size = new System.Drawing.Size(96, 13);
            this.shipping_postcodeLabel.TabIndex = 71;
            this.shipping_postcodeLabel.Text = "shipping_postcode";
            // 
            // shipping_postcodeTextBox
            // 
            this.shipping_postcodeTextBox.Location = new System.Drawing.Point(528, 206);
            this.shipping_postcodeTextBox.Name = "shipping_postcodeTextBox";
            this.shipping_postcodeTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_postcodeTextBox.TabIndex = 72;
            this.shipping_postcodeTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_postcodeTextBox_Validating);
            // 
            // shipping_countryLabel
            // 
            this.shipping_countryLabel.AutoSize = true;
            this.shipping_countryLabel.Location = new System.Drawing.Point(431, 232);
            this.shipping_countryLabel.Name = "shipping_countryLabel";
            this.shipping_countryLabel.Size = new System.Drawing.Size(87, 13);
            this.shipping_countryLabel.TabIndex = 73;
            this.shipping_countryLabel.Text = "shipping_country";
            // 
            // shipping_countryTextBox
            // 
            this.shipping_countryTextBox.Location = new System.Drawing.Point(528, 232);
            this.shipping_countryTextBox.Name = "shipping_countryTextBox";
            this.shipping_countryTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_countryTextBox.TabIndex = 74;
            this.shipping_countryTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_countryTextBox_Validating);
            // 
            // shipping_country_idLabel
            // 
            this.shipping_country_idLabel.AutoSize = true;
            this.shipping_country_idLabel.Location = new System.Drawing.Point(417, 258);
            this.shipping_country_idLabel.Name = "shipping_country_idLabel";
            this.shipping_country_idLabel.Size = new System.Drawing.Size(101, 13);
            this.shipping_country_idLabel.TabIndex = 75;
            this.shipping_country_idLabel.Text = "shipping_country_id";
            // 
            // shipping_country_idTextBox
            // 
            this.shipping_country_idTextBox.Location = new System.Drawing.Point(528, 258);
            this.shipping_country_idTextBox.Name = "shipping_country_idTextBox";
            this.shipping_country_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_country_idTextBox.TabIndex = 76;
            this.shipping_country_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_country_idTextBox_Validating);
            // 
            // shipping_zoneLabel
            // 
            this.shipping_zoneLabel.AutoSize = true;
            this.shipping_zoneLabel.Location = new System.Drawing.Point(443, 284);
            this.shipping_zoneLabel.Name = "shipping_zoneLabel";
            this.shipping_zoneLabel.Size = new System.Drawing.Size(75, 13);
            this.shipping_zoneLabel.TabIndex = 77;
            this.shipping_zoneLabel.Text = "shipping_zone";
            // 
            // shipping_zoneTextBox
            // 
            this.shipping_zoneTextBox.Location = new System.Drawing.Point(528, 284);
            this.shipping_zoneTextBox.Name = "shipping_zoneTextBox";
            this.shipping_zoneTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_zoneTextBox.TabIndex = 78;
            this.shipping_zoneTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_zoneTextBox_Validating);
            // 
            // shipping_zone_idLabel
            // 
            this.shipping_zone_idLabel.AutoSize = true;
            this.shipping_zone_idLabel.Location = new System.Drawing.Point(429, 310);
            this.shipping_zone_idLabel.Name = "shipping_zone_idLabel";
            this.shipping_zone_idLabel.Size = new System.Drawing.Size(89, 13);
            this.shipping_zone_idLabel.TabIndex = 79;
            this.shipping_zone_idLabel.Text = "shipping_zone_id";
            // 
            // shipping_zone_idTextBox
            // 
            this.shipping_zone_idTextBox.Location = new System.Drawing.Point(528, 310);
            this.shipping_zone_idTextBox.Name = "shipping_zone_idTextBox";
            this.shipping_zone_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_zone_idTextBox.TabIndex = 80;
            this.shipping_zone_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_zone_idTextBox_Validating);
            // 
            // shipping_address_formatLabel
            // 
            this.shipping_address_formatLabel.AutoSize = true;
            this.shipping_address_formatLabel.Location = new System.Drawing.Point(394, 336);
            this.shipping_address_formatLabel.Name = "shipping_address_formatLabel";
            this.shipping_address_formatLabel.Size = new System.Drawing.Size(124, 13);
            this.shipping_address_formatLabel.TabIndex = 81;
            this.shipping_address_formatLabel.Text = "shipping_address_format";
            // 
            // shipping_address_formatTextBox
            // 
            this.shipping_address_formatTextBox.Location = new System.Drawing.Point(528, 336);
            this.shipping_address_formatTextBox.Name = "shipping_address_formatTextBox";
            this.shipping_address_formatTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_address_formatTextBox.TabIndex = 82;
            this.shipping_address_formatTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_address_formatTextBox_Validating);
            // 
            // shipping_methodLabel
            // 
            this.shipping_methodLabel.AutoSize = true;
            this.shipping_methodLabel.Location = new System.Drawing.Point(431, 362);
            this.shipping_methodLabel.Name = "shipping_methodLabel";
            this.shipping_methodLabel.Size = new System.Drawing.Size(87, 13);
            this.shipping_methodLabel.TabIndex = 83;
            this.shipping_methodLabel.Text = "shipping_method";
            // 
            // shipping_methodTextBox
            // 
            this.shipping_methodTextBox.Location = new System.Drawing.Point(528, 362);
            this.shipping_methodTextBox.Name = "shipping_methodTextBox";
            this.shipping_methodTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_methodTextBox.TabIndex = 84;
            this.shipping_methodTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_methodTextBox_Validating);
            // 
            // shipping_codeLabel
            // 
            this.shipping_codeLabel.AutoSize = true;
            this.shipping_codeLabel.Location = new System.Drawing.Point(442, 388);
            this.shipping_codeLabel.Name = "shipping_codeLabel";
            this.shipping_codeLabel.Size = new System.Drawing.Size(76, 13);
            this.shipping_codeLabel.TabIndex = 85;
            this.shipping_codeLabel.Text = "shipping_code";
            // 
            // shipping_codeTextBox
            // 
            this.shipping_codeTextBox.Location = new System.Drawing.Point(528, 388);
            this.shipping_codeTextBox.Name = "shipping_codeTextBox";
            this.shipping_codeTextBox.Size = new System.Drawing.Size(100, 20);
            this.shipping_codeTextBox.TabIndex = 86;
            this.shipping_codeTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.shipping_codeTextBox_Validating);
            // 
            // commentLabel
            // 
            this.commentLabel.AutoSize = true;
            this.commentLabel.Location = new System.Drawing.Point(468, 414);
            this.commentLabel.Name = "commentLabel";
            this.commentLabel.Size = new System.Drawing.Size(50, 13);
            this.commentLabel.TabIndex = 87;
            this.commentLabel.Text = "comment";
            // 
            // commentTextBox
            // 
            this.commentTextBox.Location = new System.Drawing.Point(528, 414);
            this.commentTextBox.Name = "commentTextBox";
            this.commentTextBox.Size = new System.Drawing.Size(100, 20);
            this.commentTextBox.TabIndex = 88;
            this.commentTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.commentTextBox_Validating);
            // 
            // totalLabel
            // 
            this.totalLabel.AutoSize = true;
            this.totalLabel.Location = new System.Drawing.Point(491, 440);
            this.totalLabel.Name = "totalLabel";
            this.totalLabel.Size = new System.Drawing.Size(27, 13);
            this.totalLabel.TabIndex = 89;
            this.totalLabel.Text = "total";
            // 
            // totalTextBox
            // 
            this.totalTextBox.Location = new System.Drawing.Point(528, 440);
            this.totalTextBox.Name = "totalTextBox";
            this.totalTextBox.Size = new System.Drawing.Size(100, 20);
            this.totalTextBox.TabIndex = 90;
            this.totalTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.totalTextBox_Validating);
            // 
            // order_status_idLabel
            // 
            this.order_status_idLabel.AutoSize = true;
            this.order_status_idLabel.Location = new System.Drawing.Point(439, 466);
            this.order_status_idLabel.Name = "order_status_idLabel";
            this.order_status_idLabel.Size = new System.Drawing.Size(79, 13);
            this.order_status_idLabel.TabIndex = 91;
            this.order_status_idLabel.Text = "order_status_id";
            // 
            // order_status_idTextBox
            // 
            this.order_status_idTextBox.Location = new System.Drawing.Point(528, 466);
            this.order_status_idTextBox.Name = "order_status_idTextBox";
            this.order_status_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.order_status_idTextBox.TabIndex = 92;
            this.order_status_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.order_status_idTextBox_Validating);
            // 
            // affiliate_idLabel
            // 
            this.affiliate_idLabel.AutoSize = true;
            this.affiliate_idLabel.Location = new System.Drawing.Point(464, 492);
            this.affiliate_idLabel.Name = "affiliate_idLabel";
            this.affiliate_idLabel.Size = new System.Drawing.Size(54, 13);
            this.affiliate_idLabel.TabIndex = 93;
            this.affiliate_idLabel.Text = "affiliate_id";
            // 
            // affiliate_idTextBox
            // 
            this.affiliate_idTextBox.Location = new System.Drawing.Point(528, 492);
            this.affiliate_idTextBox.Name = "affiliate_idTextBox";
            this.affiliate_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.affiliate_idTextBox.TabIndex = 94;
            this.affiliate_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.affiliate_idTextBox_Validating);
            // 
            // commissionLabel
            // 
            this.commissionLabel.AutoSize = true;
            this.commissionLabel.Location = new System.Drawing.Point(457, 518);
            this.commissionLabel.Name = "commissionLabel";
            this.commissionLabel.Size = new System.Drawing.Size(61, 13);
            this.commissionLabel.TabIndex = 95;
            this.commissionLabel.Text = "commission";
            // 
            // commissionTextBox
            // 
            this.commissionTextBox.Location = new System.Drawing.Point(528, 518);
            this.commissionTextBox.Name = "commissionTextBox";
            this.commissionTextBox.Size = new System.Drawing.Size(100, 20);
            this.commissionTextBox.TabIndex = 96;
            this.commissionTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.commissionTextBox_Validating);
            // 
            // language_idLabel
            // 
            this.language_idLabel.AutoSize = true;
            this.language_idLabel.Location = new System.Drawing.Point(453, 544);
            this.language_idLabel.Name = "language_idLabel";
            this.language_idLabel.Size = new System.Drawing.Size(65, 13);
            this.language_idLabel.TabIndex = 97;
            this.language_idLabel.Text = "language_id";
            // 
            // language_idTextBox
            // 
            this.language_idTextBox.Location = new System.Drawing.Point(528, 544);
            this.language_idTextBox.Name = "language_idTextBox";
            this.language_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.language_idTextBox.TabIndex = 98;
            this.language_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.language_idTextBox_Validating);
            // 
            // currency_idLabel
            // 
            this.currency_idLabel.AutoSize = true;
            this.currency_idLabel.Location = new System.Drawing.Point(456, 570);
            this.currency_idLabel.Name = "currency_idLabel";
            this.currency_idLabel.Size = new System.Drawing.Size(62, 13);
            this.currency_idLabel.TabIndex = 99;
            this.currency_idLabel.Text = "currency_id";
            // 
            // currency_idTextBox
            // 
            this.currency_idTextBox.Location = new System.Drawing.Point(528, 570);
            this.currency_idTextBox.Name = "currency_idTextBox";
            this.currency_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.currency_idTextBox.TabIndex = 100;
            this.currency_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.currency_idTextBox_Validating);
            // 
            // currency_codeLabel
            // 
            this.currency_codeLabel.AutoSize = true;
            this.currency_codeLabel.Location = new System.Drawing.Point(440, 596);
            this.currency_codeLabel.Name = "currency_codeLabel";
            this.currency_codeLabel.Size = new System.Drawing.Size(78, 13);
            this.currency_codeLabel.TabIndex = 101;
            this.currency_codeLabel.Text = "currency_code";
            // 
            // currency_codeTextBox
            // 
            this.currency_codeTextBox.Location = new System.Drawing.Point(528, 596);
            this.currency_codeTextBox.Name = "currency_codeTextBox";
            this.currency_codeTextBox.Size = new System.Drawing.Size(100, 20);
            this.currency_codeTextBox.TabIndex = 102;
            this.currency_codeTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.currency_codeTextBox_Validating);
            // 
            // currency_valueLabel
            // 
            this.currency_valueLabel.AutoSize = true;
            this.currency_valueLabel.Location = new System.Drawing.Point(438, 622);
            this.currency_valueLabel.Name = "currency_valueLabel";
            this.currency_valueLabel.Size = new System.Drawing.Size(80, 13);
            this.currency_valueLabel.TabIndex = 103;
            this.currency_valueLabel.Text = "currency_value";
            // 
            // currency_valueTextBox
            // 
            this.currency_valueTextBox.Location = new System.Drawing.Point(528, 622);
            this.currency_valueTextBox.Name = "currency_valueTextBox";
            this.currency_valueTextBox.Size = new System.Drawing.Size(100, 20);
            this.currency_valueTextBox.TabIndex = 104;
            this.currency_valueTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.currency_valueTextBox_Validating);
            // 
            // ipLabel
            // 
            this.ipLabel.AutoSize = true;
            this.ipLabel.Location = new System.Drawing.Point(503, 648);
            this.ipLabel.Name = "ipLabel";
            this.ipLabel.Size = new System.Drawing.Size(15, 13);
            this.ipLabel.TabIndex = 105;
            this.ipLabel.Text = "ip";
            // 
            // ipTextBox
            // 
            this.ipTextBox.Location = new System.Drawing.Point(528, 648);
            this.ipTextBox.Name = "ipTextBox";
            this.ipTextBox.Size = new System.Drawing.Size(100, 20);
            this.ipTextBox.TabIndex = 106;
            this.ipTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.ipTextBox_Validating);
            // 
            // forwarded_ipLabel
            // 
            this.forwarded_ipLabel.AutoSize = true;
            this.forwarded_ipLabel.Location = new System.Drawing.Point(450, 674);
            this.forwarded_ipLabel.Name = "forwarded_ipLabel";
            this.forwarded_ipLabel.Size = new System.Drawing.Size(68, 13);
            this.forwarded_ipLabel.TabIndex = 107;
            this.forwarded_ipLabel.Text = "forwarded_ip";
            // 
            // forwarded_ipTextBox
            // 
            this.forwarded_ipTextBox.Location = new System.Drawing.Point(528, 674);
            this.forwarded_ipTextBox.Name = "forwarded_ipTextBox";
            this.forwarded_ipTextBox.Size = new System.Drawing.Size(100, 20);
            this.forwarded_ipTextBox.TabIndex = 108;
            this.forwarded_ipTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.forwarded_ipTextBox_Validating);
            // 
            // user_agentLabel
            // 
            this.user_agentLabel.AutoSize = true;
            this.user_agentLabel.Location = new System.Drawing.Point(458, 700);
            this.user_agentLabel.Name = "user_agentLabel";
            this.user_agentLabel.Size = new System.Drawing.Size(60, 13);
            this.user_agentLabel.TabIndex = 109;
            this.user_agentLabel.Text = "user_agent";
            // 
            // user_agentTextBox
            // 
            this.user_agentTextBox.Location = new System.Drawing.Point(528, 700);
            this.user_agentTextBox.Name = "user_agentTextBox";
            this.user_agentTextBox.Size = new System.Drawing.Size(100, 20);
            this.user_agentTextBox.TabIndex = 110;
            this.user_agentTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.user_agentTextBox_Validating);
            // 
            // accept_languageLabel
            // 
            this.accept_languageLabel.AutoSize = true;
            this.accept_languageLabel.Location = new System.Drawing.Point(428, 726);
            this.accept_languageLabel.Name = "accept_languageLabel";
            this.accept_languageLabel.Size = new System.Drawing.Size(90, 13);
            this.accept_languageLabel.TabIndex = 111;
            this.accept_languageLabel.Text = "accept_language";
            // 
            // accept_languageTextBox
            // 
            this.accept_languageTextBox.Location = new System.Drawing.Point(528, 726);
            this.accept_languageTextBox.Name = "accept_languageTextBox";
            this.accept_languageTextBox.Size = new System.Drawing.Size(100, 20);
            this.accept_languageTextBox.TabIndex = 112;
            this.accept_languageTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.accept_languageTextBox_Validating);
            // 
            // date_addedLabel
            // 
            this.date_addedLabel.AutoSize = true;
            this.date_addedLabel.Location = new System.Drawing.Point(454, 752);
            this.date_addedLabel.Name = "date_addedLabel";
            this.date_addedLabel.Size = new System.Drawing.Size(64, 13);
            this.date_addedLabel.TabIndex = 113;
            this.date_addedLabel.Text = "date_added";
            // 
            // date_added_dateTimePicker
            // 
            this.date_added_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm";
            this.date_added_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.date_added_dateTimePicker.Location = new System.Drawing.Point(528, 752);
            this.date_added_dateTimePicker.Name = "date_added_dateTimePicker";
            this.date_added_dateTimePicker.Size = new System.Drawing.Size(200, 20);
            this.date_added_dateTimePicker.TabIndex = 114;
            this.date_added_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
            // 
            // date_modifiedLabel
            // 
            this.date_modifiedLabel.AutoSize = true;
            this.date_modifiedLabel.Location = new System.Drawing.Point(445, 778);
            this.date_modifiedLabel.Name = "date_modifiedLabel";
            this.date_modifiedLabel.Size = new System.Drawing.Size(73, 13);
            this.date_modifiedLabel.TabIndex = 115;
            this.date_modifiedLabel.Text = "date_modified";
            // 
            // date_modified_dateTimePicker
            // 
            this.date_modified_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm";
            this.date_modified_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.date_modified_dateTimePicker.Location = new System.Drawing.Point(528, 778);
            this.date_modified_dateTimePicker.Name = "date_modified_dateTimePicker";
            this.date_modified_dateTimePicker.Size = new System.Drawing.Size(200, 20);
            this.date_modified_dateTimePicker.TabIndex = 116;
            this.date_modified_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.Panel1);
            this.panel3.Controls.Add(this.panel4);
            this.panel3.Controls.Add(this.panel5);
            this.panel3.Controls.Add(this.panel6);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel3.Location = new System.Drawing.Point(0, 25);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(806, 494);
            this.panel3.TabIndex = 19;
            // 
            // panel4
            // 
            this.panel4.Dock = System.Windows.Forms.DockStyle.Right;
            this.panel4.Location = new System.Drawing.Point(796, 0);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(10, 484);
            this.panel4.TabIndex = 3;
            // 
            // panel5
            // 
            this.panel5.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel5.Location = new System.Drawing.Point(0, 0);
            this.panel5.Name = "panel5";
            this.panel5.Size = new System.Drawing.Size(10, 484);
            this.panel5.TabIndex = 5;
            // 
            // panel6
            // 
            this.panel6.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel6.Location = new System.Drawing.Point(0, 484);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(806, 10);
            this.panel6.TabIndex = 6;
            // 
            // frmoc_order
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.ClientSize = new System.Drawing.Size(806, 519);
            this.Controls.Add(this.panel3);
            this.Controls.Add(this.bindingNavigator1);
            this.Name = "frmoc_order";
            this.Text = "Oc_Order";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmoc_order_FormClosing);
            this.Load += new System.EventHandler(this.frmoc_order_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).EndInit();
            this.bindingNavigator1.ResumeLayout(false);
            this.bindingNavigator1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.oc_orderBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.Panel1.ResumeLayout(false);
            this.Panel1.PerformLayout();
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

		}
		
		#endregion
		
		private System.Windows.Forms.BindingNavigator bindingNavigator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorAddNewItem;
		private System.Windows.Forms.ToolStripLabel bindingNavigatorCountItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorDeleteItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveFirstItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMovePreviousItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator;
		private System.Windows.Forms.ToolStripTextBox bindingNavigatorPositionItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveNextItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveLastItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator2;
		private System.Windows.Forms.ToolStripButton toolStripButton1;
		private System.Windows.Forms.ErrorProvider errorProvider1;
		private System.Windows.Forms.Panel Panel1;
		private System.Windows.Forms.BindingSource oc_orderBindingSource;
		private System.Windows.Forms.TextBox order_idTextBox;
		private System.Windows.Forms.Label order_idLabel;
		private System.Windows.Forms.TextBox invoice_noTextBox;
		private System.Windows.Forms.Label invoice_noLabel;
		private System.Windows.Forms.TextBox invoice_prefixTextBox;
		private System.Windows.Forms.Label invoice_prefixLabel;
		private System.Windows.Forms.TextBox store_idTextBox;
		private System.Windows.Forms.Label store_idLabel;
		private System.Windows.Forms.TextBox store_nameTextBox;
		private System.Windows.Forms.Label store_nameLabel;
		private System.Windows.Forms.TextBox store_urlTextBox;
		private System.Windows.Forms.Label store_urlLabel;
		private System.Windows.Forms.TextBox customer_idTextBox;
		private System.Windows.Forms.Label customer_idLabel;
		private System.Windows.Forms.TextBox customer_group_idTextBox;
		private System.Windows.Forms.Label customer_group_idLabel;
		private System.Windows.Forms.TextBox firstnameTextBox;
		private System.Windows.Forms.Label firstnameLabel;
		private System.Windows.Forms.TextBox lastnameTextBox;
		private System.Windows.Forms.Label lastnameLabel;
		private System.Windows.Forms.TextBox emailTextBox;
		private System.Windows.Forms.Label emailLabel;
		private System.Windows.Forms.TextBox telephoneTextBox;
		private System.Windows.Forms.Label telephoneLabel;
		private System.Windows.Forms.TextBox faxTextBox;
		private System.Windows.Forms.Label faxLabel;
		private System.Windows.Forms.TextBox payment_firstnameTextBox;
		private System.Windows.Forms.Label payment_firstnameLabel;
		private System.Windows.Forms.TextBox payment_lastnameTextBox;
		private System.Windows.Forms.Label payment_lastnameLabel;
		private System.Windows.Forms.TextBox payment_companyTextBox;
		private System.Windows.Forms.Label payment_companyLabel;
		private System.Windows.Forms.TextBox payment_company_idTextBox;
		private System.Windows.Forms.Label payment_company_idLabel;
		private System.Windows.Forms.TextBox payment_tax_idTextBox;
		private System.Windows.Forms.Label payment_tax_idLabel;
		private System.Windows.Forms.TextBox payment_address_1TextBox;
		private System.Windows.Forms.Label payment_address_1Label;
		private System.Windows.Forms.TextBox payment_address_2TextBox;
		private System.Windows.Forms.Label payment_address_2Label;
		private System.Windows.Forms.TextBox payment_cityTextBox;
		private System.Windows.Forms.Label payment_cityLabel;
		private System.Windows.Forms.TextBox payment_postcodeTextBox;
		private System.Windows.Forms.Label payment_postcodeLabel;
		private System.Windows.Forms.TextBox payment_countryTextBox;
		private System.Windows.Forms.Label payment_countryLabel;
		private System.Windows.Forms.TextBox payment_country_idTextBox;
		private System.Windows.Forms.Label payment_country_idLabel;
		private System.Windows.Forms.TextBox payment_zoneTextBox;
		private System.Windows.Forms.Label payment_zoneLabel;
		private System.Windows.Forms.TextBox payment_zone_idTextBox;
		private System.Windows.Forms.Label payment_zone_idLabel;
		private System.Windows.Forms.TextBox payment_address_formatTextBox;
		private System.Windows.Forms.Label payment_address_formatLabel;
		private System.Windows.Forms.TextBox payment_methodTextBox;
		private System.Windows.Forms.Label payment_methodLabel;
		private System.Windows.Forms.TextBox payment_codeTextBox;
		private System.Windows.Forms.Label payment_codeLabel;
		private System.Windows.Forms.TextBox shipping_firstnameTextBox;
		private System.Windows.Forms.Label shipping_firstnameLabel;
		private System.Windows.Forms.TextBox shipping_lastnameTextBox;
		private System.Windows.Forms.Label shipping_lastnameLabel;
		private System.Windows.Forms.TextBox shipping_companyTextBox;
		private System.Windows.Forms.Label shipping_companyLabel;
		private System.Windows.Forms.TextBox shipping_address_1TextBox;
		private System.Windows.Forms.Label shipping_address_1Label;
		private System.Windows.Forms.TextBox shipping_address_2TextBox;
		private System.Windows.Forms.Label shipping_address_2Label;
		private System.Windows.Forms.TextBox shipping_cityTextBox;
		private System.Windows.Forms.Label shipping_cityLabel;
		private System.Windows.Forms.TextBox shipping_postcodeTextBox;
		private System.Windows.Forms.Label shipping_postcodeLabel;
		private System.Windows.Forms.TextBox shipping_countryTextBox;
		private System.Windows.Forms.Label shipping_countryLabel;
		private System.Windows.Forms.TextBox shipping_country_idTextBox;
		private System.Windows.Forms.Label shipping_country_idLabel;
		private System.Windows.Forms.TextBox shipping_zoneTextBox;
		private System.Windows.Forms.Label shipping_zoneLabel;
		private System.Windows.Forms.TextBox shipping_zone_idTextBox;
		private System.Windows.Forms.Label shipping_zone_idLabel;
		private System.Windows.Forms.TextBox shipping_address_formatTextBox;
		private System.Windows.Forms.Label shipping_address_formatLabel;
		private System.Windows.Forms.TextBox shipping_methodTextBox;
		private System.Windows.Forms.Label shipping_methodLabel;
		private System.Windows.Forms.TextBox shipping_codeTextBox;
		private System.Windows.Forms.Label shipping_codeLabel;
		private System.Windows.Forms.TextBox commentTextBox;
		private System.Windows.Forms.Label commentLabel;
		private System.Windows.Forms.TextBox totalTextBox;
		private System.Windows.Forms.Label totalLabel;
		private System.Windows.Forms.TextBox order_status_idTextBox;
		private System.Windows.Forms.Label order_status_idLabel;
		private System.Windows.Forms.TextBox affiliate_idTextBox;
		private System.Windows.Forms.Label affiliate_idLabel;
		private System.Windows.Forms.TextBox commissionTextBox;
		private System.Windows.Forms.Label commissionLabel;
		private System.Windows.Forms.TextBox language_idTextBox;
		private System.Windows.Forms.Label language_idLabel;
		private System.Windows.Forms.TextBox currency_idTextBox;
		private System.Windows.Forms.Label currency_idLabel;
		private System.Windows.Forms.TextBox currency_codeTextBox;
		private System.Windows.Forms.Label currency_codeLabel;
		private System.Windows.Forms.TextBox currency_valueTextBox;
		private System.Windows.Forms.Label currency_valueLabel;
		private System.Windows.Forms.TextBox ipTextBox;
		private System.Windows.Forms.Label ipLabel;
		private System.Windows.Forms.TextBox forwarded_ipTextBox;
		private System.Windows.Forms.Label forwarded_ipLabel;
		private System.Windows.Forms.TextBox user_agentTextBox;
		private System.Windows.Forms.Label user_agentLabel;
		private System.Windows.Forms.TextBox accept_languageTextBox;
		private System.Windows.Forms.Label accept_languageLabel;
		private System.Windows.Forms.DateTimePicker date_added_dateTimePicker;
		private System.Windows.Forms.Label date_addedLabel;
		private System.Windows.Forms.DateTimePicker date_modified_dateTimePicker;
		private System.Windows.Forms.Label date_modifiedLabel;
		private System.Windows.Forms.Panel panel3;
		private System.Windows.Forms.Panel panel4;
		private System.Windows.Forms.Panel panel5;
		private System.Windows.Forms.Panel panel6;
		
	}
}

