/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

namespace MureOcart
{
	partial class frmoc_product
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmoc_product));
            this.bindingNavigator1 = new System.Windows.Forms.BindingNavigator(this.components);
            this.bindingNavigatorCountItem = new System.Windows.Forms.ToolStripLabel();
            this.bindingNavigatorDeleteItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMoveFirstItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMovePreviousItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorSeparator = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorPositionItem = new System.Windows.Forms.ToolStripTextBox();
            this.bindingNavigatorSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorMoveNextItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorMoveLastItem = new System.Windows.Forms.ToolStripButton();
            this.bindingNavigatorSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.bindingNavigatorAddNewItem = new System.Windows.Forms.ToolStripButton();
            this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
            this.oc_productBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.Panel1 = new System.Windows.Forms.Panel();
            this.product_idLabel = new System.Windows.Forms.Label();
            this.product_idTextBox = new System.Windows.Forms.TextBox();
            this.modelLabel = new System.Windows.Forms.Label();
            this.modelTextBox = new System.Windows.Forms.TextBox();
            this.skuLabel = new System.Windows.Forms.Label();
            this.skuTextBox = new System.Windows.Forms.TextBox();
            this.upcLabel = new System.Windows.Forms.Label();
            this.upcTextBox = new System.Windows.Forms.TextBox();
            this.eanLabel = new System.Windows.Forms.Label();
            this.eanTextBox = new System.Windows.Forms.TextBox();
            this.janLabel = new System.Windows.Forms.Label();
            this.janTextBox = new System.Windows.Forms.TextBox();
            this.isbnLabel = new System.Windows.Forms.Label();
            this.isbnTextBox = new System.Windows.Forms.TextBox();
            this.mpnLabel = new System.Windows.Forms.Label();
            this.mpnTextBox = new System.Windows.Forms.TextBox();
            this.locationLabel = new System.Windows.Forms.Label();
            this.locationTextBox = new System.Windows.Forms.TextBox();
            this.quantityLabel = new System.Windows.Forms.Label();
            this.quantityTextBox = new System.Windows.Forms.TextBox();
            this.stock_status_idLabel = new System.Windows.Forms.Label();
            this.stock_status_idTextBox = new System.Windows.Forms.TextBox();
            this.imageLabel = new System.Windows.Forms.Label();
            this.imageTextBox = new System.Windows.Forms.TextBox();
            this.manufacturer_idLabel = new System.Windows.Forms.Label();
            this.manufacturer_idTextBox = new System.Windows.Forms.TextBox();
            this.shippingLabel = new System.Windows.Forms.Label();
            this.shippingCheckBox = new System.Windows.Forms.CheckBox();
            this.priceLabel = new System.Windows.Forms.Label();
            this.priceTextBox = new System.Windows.Forms.TextBox();
            this.pointsLabel = new System.Windows.Forms.Label();
            this.pointsTextBox = new System.Windows.Forms.TextBox();
            this.tax_class_idLabel = new System.Windows.Forms.Label();
            this.tax_class_idTextBox = new System.Windows.Forms.TextBox();
            this.date_availableLabel = new System.Windows.Forms.Label();
            this.date_available_dateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.weightLabel = new System.Windows.Forms.Label();
            this.weightTextBox = new System.Windows.Forms.TextBox();
            this.weight_class_idLabel = new System.Windows.Forms.Label();
            this.weight_class_idTextBox = new System.Windows.Forms.TextBox();
            this.lengthLabel = new System.Windows.Forms.Label();
            this.lengthTextBox = new System.Windows.Forms.TextBox();
            this.widthLabel = new System.Windows.Forms.Label();
            this.widthTextBox = new System.Windows.Forms.TextBox();
            this.heightLabel = new System.Windows.Forms.Label();
            this.heightTextBox = new System.Windows.Forms.TextBox();
            this.length_class_idLabel = new System.Windows.Forms.Label();
            this.length_class_idTextBox = new System.Windows.Forms.TextBox();
            this.subtractLabel = new System.Windows.Forms.Label();
            this.subtractCheckBox = new System.Windows.Forms.CheckBox();
            this.minimumLabel = new System.Windows.Forms.Label();
            this.minimumTextBox = new System.Windows.Forms.TextBox();
            this.sort_orderLabel = new System.Windows.Forms.Label();
            this.sort_orderTextBox = new System.Windows.Forms.TextBox();
            this.statusLabel = new System.Windows.Forms.Label();
            this.statusCheckBox = new System.Windows.Forms.CheckBox();
            this.date_addedLabel = new System.Windows.Forms.Label();
            this.date_added_dateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.date_modifiedLabel = new System.Windows.Forms.Label();
            this.date_modified_dateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.viewedLabel = new System.Windows.Forms.Label();
            this.viewedTextBox = new System.Windows.Forms.TextBox();
            this.quantity_setLabel = new System.Windows.Forms.Label();
            this.quantity_setTextBox = new System.Windows.Forms.TextBox();
            this.panel3 = new System.Windows.Forms.Panel();
            this.panel4 = new System.Windows.Forms.Panel();
            this.panel5 = new System.Windows.Forms.Panel();
            this.panel6 = new System.Windows.Forms.Panel();
            ((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).BeginInit();
            this.bindingNavigator1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.oc_productBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.Panel1.SuspendLayout();
            this.panel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // bindingNavigator1
            // 
            this.bindingNavigator1.AddNewItem = null;
            this.bindingNavigator1.BindingSource = this.oc_productBindingSource;
            this.bindingNavigator1.CountItem = this.bindingNavigatorCountItem;
            this.bindingNavigator1.DeleteItem = this.bindingNavigatorDeleteItem;
            this.bindingNavigator1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.bindingNavigatorMoveFirstItem,
            this.bindingNavigatorMovePreviousItem,
            this.bindingNavigatorSeparator,
            this.bindingNavigatorPositionItem,
            this.bindingNavigatorCountItem,
            this.bindingNavigatorSeparator1,
            this.bindingNavigatorMoveNextItem,
            this.bindingNavigatorMoveLastItem,
            this.bindingNavigatorSeparator2,
            this.bindingNavigatorAddNewItem,
            this.bindingNavigatorDeleteItem,
            this.toolStripButton1});
            this.bindingNavigator1.Location = new System.Drawing.Point(0, 0);
            this.bindingNavigator1.MoveFirstItem = this.bindingNavigatorMoveFirstItem;
            this.bindingNavigator1.MoveLastItem = this.bindingNavigatorMoveLastItem;
            this.bindingNavigator1.MoveNextItem = this.bindingNavigatorMoveNextItem;
            this.bindingNavigator1.MovePreviousItem = this.bindingNavigatorMovePreviousItem;
            this.bindingNavigator1.Name = "bindingNavigator1";
            this.bindingNavigator1.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.bindingNavigator1.PositionItem = this.bindingNavigatorPositionItem;
            this.bindingNavigator1.Size = new System.Drawing.Size(782, 25);
            this.bindingNavigator1.TabIndex = 0;
            this.bindingNavigator1.Text = "bindingNavigator1";
            // 
            // bindingNavigatorCountItem
            // 
            this.bindingNavigatorCountItem.Name = "bindingNavigatorCountItem";
            this.bindingNavigatorCountItem.Size = new System.Drawing.Size(35, 22);
            this.bindingNavigatorCountItem.Text = "of {0}";
            this.bindingNavigatorCountItem.ToolTipText = "Total number of items";
            // 
            // bindingNavigatorDeleteItem
            // 
            this.bindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorDeleteItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorDeleteItem.Image")));
            this.bindingNavigatorDeleteItem.Name = "bindingNavigatorDeleteItem";
            this.bindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorDeleteItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorDeleteItem.Text = "Delete";
            // 
            // bindingNavigatorMoveFirstItem
            // 
            this.bindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveFirstItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveFirstItem.Image")));
            this.bindingNavigatorMoveFirstItem.Name = "bindingNavigatorMoveFirstItem";
            this.bindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveFirstItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveFirstItem.Text = "Move first";
            // 
            // bindingNavigatorMovePreviousItem
            // 
            this.bindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMovePreviousItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMovePreviousItem.Image")));
            this.bindingNavigatorMovePreviousItem.Name = "bindingNavigatorMovePreviousItem";
            this.bindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMovePreviousItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMovePreviousItem.Text = "Move previous";
            // 
            // bindingNavigatorSeparator
            // 
            this.bindingNavigatorSeparator.Name = "bindingNavigatorSeparator";
            this.bindingNavigatorSeparator.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorPositionItem
            // 
            this.bindingNavigatorPositionItem.AccessibleName = "Position";
            this.bindingNavigatorPositionItem.AutoSize = false;
            this.bindingNavigatorPositionItem.Name = "bindingNavigatorPositionItem";
            this.bindingNavigatorPositionItem.Size = new System.Drawing.Size(50, 23);
            this.bindingNavigatorPositionItem.Text = "0";
            this.bindingNavigatorPositionItem.ToolTipText = "Current position";
            // 
            // bindingNavigatorSeparator1
            // 
            this.bindingNavigatorSeparator1.Name = "bindingNavigatorSeparator1";
            this.bindingNavigatorSeparator1.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorMoveNextItem
            // 
            this.bindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveNextItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveNextItem.Image")));
            this.bindingNavigatorMoveNextItem.Name = "bindingNavigatorMoveNextItem";
            this.bindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveNextItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveNextItem.Text = "Move next";
            // 
            // bindingNavigatorMoveLastItem
            // 
            this.bindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorMoveLastItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveLastItem.Image")));
            this.bindingNavigatorMoveLastItem.Name = "bindingNavigatorMoveLastItem";
            this.bindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorMoveLastItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorMoveLastItem.Text = "Move last";
            // 
            // bindingNavigatorSeparator2
            // 
            this.bindingNavigatorSeparator2.Name = "bindingNavigatorSeparator2";
            this.bindingNavigatorSeparator2.Size = new System.Drawing.Size(6, 25);
            // 
            // bindingNavigatorAddNewItem
            // 
            this.bindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.bindingNavigatorAddNewItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorAddNewItem.Image")));
            this.bindingNavigatorAddNewItem.Name = "bindingNavigatorAddNewItem";
            this.bindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = true;
            this.bindingNavigatorAddNewItem.Size = new System.Drawing.Size(23, 22);
            this.bindingNavigatorAddNewItem.Text = "Add new";
            this.bindingNavigatorAddNewItem.Click += new System.EventHandler(this.bindingNavigatorAddNewItem_Click);
            // 
            // toolStripButton1
            // 
            this.toolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButton1.Image")));
            this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButton1.Name = "toolStripButton1";
            this.toolStripButton1.Size = new System.Drawing.Size(23, 22);
            this.toolStripButton1.Text = "Save";
            this.toolStripButton1.Click += new System.EventHandler(this.Save_Click);
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // Panel1
            // 
            this.Panel1.AutoScroll = true;
            this.Panel1.AutoSize = true;
            this.Panel1.Controls.Add(this.product_idLabel);
            this.Panel1.Controls.Add(this.product_idTextBox);
            this.Panel1.Controls.Add(this.modelLabel);
            this.Panel1.Controls.Add(this.modelTextBox);
            this.Panel1.Controls.Add(this.skuLabel);
            this.Panel1.Controls.Add(this.skuTextBox);
            this.Panel1.Controls.Add(this.upcLabel);
            this.Panel1.Controls.Add(this.upcTextBox);
            this.Panel1.Controls.Add(this.eanLabel);
            this.Panel1.Controls.Add(this.eanTextBox);
            this.Panel1.Controls.Add(this.janLabel);
            this.Panel1.Controls.Add(this.janTextBox);
            this.Panel1.Controls.Add(this.isbnLabel);
            this.Panel1.Controls.Add(this.isbnTextBox);
            this.Panel1.Controls.Add(this.mpnLabel);
            this.Panel1.Controls.Add(this.mpnTextBox);
            this.Panel1.Controls.Add(this.locationLabel);
            this.Panel1.Controls.Add(this.locationTextBox);
            this.Panel1.Controls.Add(this.quantityLabel);
            this.Panel1.Controls.Add(this.quantityTextBox);
            this.Panel1.Controls.Add(this.stock_status_idLabel);
            this.Panel1.Controls.Add(this.stock_status_idTextBox);
            this.Panel1.Controls.Add(this.imageLabel);
            this.Panel1.Controls.Add(this.imageTextBox);
            this.Panel1.Controls.Add(this.manufacturer_idLabel);
            this.Panel1.Controls.Add(this.manufacturer_idTextBox);
            this.Panel1.Controls.Add(this.shippingLabel);
            this.Panel1.Controls.Add(this.shippingCheckBox);
            this.Panel1.Controls.Add(this.priceLabel);
            this.Panel1.Controls.Add(this.priceTextBox);
            this.Panel1.Controls.Add(this.pointsLabel);
            this.Panel1.Controls.Add(this.pointsTextBox);
            this.Panel1.Controls.Add(this.tax_class_idLabel);
            this.Panel1.Controls.Add(this.tax_class_idTextBox);
            this.Panel1.Controls.Add(this.date_availableLabel);
            this.Panel1.Controls.Add(this.date_available_dateTimePicker);
            this.Panel1.Controls.Add(this.weightLabel);
            this.Panel1.Controls.Add(this.weightTextBox);
            this.Panel1.Controls.Add(this.weight_class_idLabel);
            this.Panel1.Controls.Add(this.weight_class_idTextBox);
            this.Panel1.Controls.Add(this.lengthLabel);
            this.Panel1.Controls.Add(this.lengthTextBox);
            this.Panel1.Controls.Add(this.widthLabel);
            this.Panel1.Controls.Add(this.widthTextBox);
            this.Panel1.Controls.Add(this.heightLabel);
            this.Panel1.Controls.Add(this.heightTextBox);
            this.Panel1.Controls.Add(this.length_class_idLabel);
            this.Panel1.Controls.Add(this.length_class_idTextBox);
            this.Panel1.Controls.Add(this.subtractLabel);
            this.Panel1.Controls.Add(this.subtractCheckBox);
            this.Panel1.Controls.Add(this.minimumLabel);
            this.Panel1.Controls.Add(this.minimumTextBox);
            this.Panel1.Controls.Add(this.sort_orderLabel);
            this.Panel1.Controls.Add(this.sort_orderTextBox);
            this.Panel1.Controls.Add(this.statusLabel);
            this.Panel1.Controls.Add(this.statusCheckBox);
            this.Panel1.Controls.Add(this.date_addedLabel);
            this.Panel1.Controls.Add(this.date_added_dateTimePicker);
            this.Panel1.Controls.Add(this.date_modifiedLabel);
            this.Panel1.Controls.Add(this.date_modified_dateTimePicker);
            this.Panel1.Controls.Add(this.viewedLabel);
            this.Panel1.Controls.Add(this.viewedTextBox);
            this.Panel1.Controls.Add(this.quantity_setLabel);
            this.Panel1.Controls.Add(this.quantity_setTextBox);
            this.Panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Panel1.Location = new System.Drawing.Point(10, 0);
            this.Panel1.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
            this.Panel1.Name = "Panel1";
            this.Panel1.Size = new System.Drawing.Size(762, 431);
            this.Panel1.TabIndex = 1;
            // 
            // product_idLabel
            // 
            this.product_idLabel.AutoSize = true;
            this.product_idLabel.Location = new System.Drawing.Point(74, 50);
            this.product_idLabel.Name = "product_idLabel";
            this.product_idLabel.Size = new System.Drawing.Size(57, 13);
            this.product_idLabel.TabIndex = 1;
            this.product_idLabel.Text = "product_id";
            // 
            // product_idTextBox
            // 
            this.product_idTextBox.Location = new System.Drawing.Point(141, 50);
            this.product_idTextBox.Name = "product_idTextBox";
            this.product_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.product_idTextBox.TabIndex = 2;
            this.product_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.product_idTextBox_Validating);
            // 
            // modelLabel
            // 
            this.modelLabel.AutoSize = true;
            this.modelLabel.Location = new System.Drawing.Point(96, 76);
            this.modelLabel.Name = "modelLabel";
            this.modelLabel.Size = new System.Drawing.Size(35, 13);
            this.modelLabel.TabIndex = 3;
            this.modelLabel.Text = "model";
            // 
            // modelTextBox
            // 
            this.modelTextBox.Location = new System.Drawing.Point(141, 76);
            this.modelTextBox.Name = "modelTextBox";
            this.modelTextBox.Size = new System.Drawing.Size(100, 20);
            this.modelTextBox.TabIndex = 4;
            this.modelTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.modelTextBox_Validating);
            // 
            // skuLabel
            // 
            this.skuLabel.AutoSize = true;
            this.skuLabel.Location = new System.Drawing.Point(107, 102);
            this.skuLabel.Name = "skuLabel";
            this.skuLabel.Size = new System.Drawing.Size(24, 13);
            this.skuLabel.TabIndex = 5;
            this.skuLabel.Text = "sku";
            // 
            // skuTextBox
            // 
            this.skuTextBox.Location = new System.Drawing.Point(141, 102);
            this.skuTextBox.Name = "skuTextBox";
            this.skuTextBox.Size = new System.Drawing.Size(100, 20);
            this.skuTextBox.TabIndex = 6;
            this.skuTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.skuTextBox_Validating);
            // 
            // upcLabel
            // 
            this.upcLabel.AutoSize = true;
            this.upcLabel.Location = new System.Drawing.Point(106, 128);
            this.upcLabel.Name = "upcLabel";
            this.upcLabel.Size = new System.Drawing.Size(25, 13);
            this.upcLabel.TabIndex = 7;
            this.upcLabel.Text = "upc";
            // 
            // upcTextBox
            // 
            this.upcTextBox.Location = new System.Drawing.Point(141, 128);
            this.upcTextBox.Name = "upcTextBox";
            this.upcTextBox.Size = new System.Drawing.Size(100, 20);
            this.upcTextBox.TabIndex = 8;
            this.upcTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.upcTextBox_Validating);
            // 
            // eanLabel
            // 
            this.eanLabel.AutoSize = true;
            this.eanLabel.Location = new System.Drawing.Point(106, 154);
            this.eanLabel.Name = "eanLabel";
            this.eanLabel.Size = new System.Drawing.Size(25, 13);
            this.eanLabel.TabIndex = 9;
            this.eanLabel.Text = "ean";
            // 
            // eanTextBox
            // 
            this.eanTextBox.Location = new System.Drawing.Point(141, 154);
            this.eanTextBox.Name = "eanTextBox";
            this.eanTextBox.Size = new System.Drawing.Size(100, 20);
            this.eanTextBox.TabIndex = 10;
            this.eanTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.eanTextBox_Validating);
            // 
            // janLabel
            // 
            this.janLabel.AutoSize = true;
            this.janLabel.Location = new System.Drawing.Point(110, 180);
            this.janLabel.Name = "janLabel";
            this.janLabel.Size = new System.Drawing.Size(21, 13);
            this.janLabel.TabIndex = 11;
            this.janLabel.Text = "jan";
            // 
            // janTextBox
            // 
            this.janTextBox.Location = new System.Drawing.Point(141, 180);
            this.janTextBox.Name = "janTextBox";
            this.janTextBox.Size = new System.Drawing.Size(100, 20);
            this.janTextBox.TabIndex = 12;
            this.janTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.janTextBox_Validating);
            // 
            // isbnLabel
            // 
            this.isbnLabel.AutoSize = true;
            this.isbnLabel.Location = new System.Drawing.Point(105, 206);
            this.isbnLabel.Name = "isbnLabel";
            this.isbnLabel.Size = new System.Drawing.Size(26, 13);
            this.isbnLabel.TabIndex = 13;
            this.isbnLabel.Text = "isbn";
            // 
            // isbnTextBox
            // 
            this.isbnTextBox.Location = new System.Drawing.Point(141, 206);
            this.isbnTextBox.Name = "isbnTextBox";
            this.isbnTextBox.Size = new System.Drawing.Size(100, 20);
            this.isbnTextBox.TabIndex = 14;
            this.isbnTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.isbnTextBox_Validating);
            // 
            // mpnLabel
            // 
            this.mpnLabel.AutoSize = true;
            this.mpnLabel.Location = new System.Drawing.Point(104, 232);
            this.mpnLabel.Name = "mpnLabel";
            this.mpnLabel.Size = new System.Drawing.Size(27, 13);
            this.mpnLabel.TabIndex = 15;
            this.mpnLabel.Text = "mpn";
            // 
            // mpnTextBox
            // 
            this.mpnTextBox.Location = new System.Drawing.Point(141, 232);
            this.mpnTextBox.Name = "mpnTextBox";
            this.mpnTextBox.Size = new System.Drawing.Size(100, 20);
            this.mpnTextBox.TabIndex = 16;
            this.mpnTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.mpnTextBox_Validating);
            // 
            // locationLabel
            // 
            this.locationLabel.AutoSize = true;
            this.locationLabel.Location = new System.Drawing.Point(87, 258);
            this.locationLabel.Name = "locationLabel";
            this.locationLabel.Size = new System.Drawing.Size(44, 13);
            this.locationLabel.TabIndex = 17;
            this.locationLabel.Text = "location";
            // 
            // locationTextBox
            // 
            this.locationTextBox.Location = new System.Drawing.Point(141, 258);
            this.locationTextBox.Name = "locationTextBox";
            this.locationTextBox.Size = new System.Drawing.Size(100, 20);
            this.locationTextBox.TabIndex = 18;
            this.locationTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.locationTextBox_Validating);
            // 
            // quantityLabel
            // 
            this.quantityLabel.AutoSize = true;
            this.quantityLabel.Location = new System.Drawing.Point(87, 284);
            this.quantityLabel.Name = "quantityLabel";
            this.quantityLabel.Size = new System.Drawing.Size(44, 13);
            this.quantityLabel.TabIndex = 19;
            this.quantityLabel.Text = "quantity";
            // 
            // quantityTextBox
            // 
            this.quantityTextBox.Location = new System.Drawing.Point(141, 284);
            this.quantityTextBox.Name = "quantityTextBox";
            this.quantityTextBox.Size = new System.Drawing.Size(100, 20);
            this.quantityTextBox.TabIndex = 20;
            this.quantityTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.quantityTextBox_Validating);
            // 
            // stock_status_idLabel
            // 
            this.stock_status_idLabel.AutoSize = true;
            this.stock_status_idLabel.Location = new System.Drawing.Point(50, 310);
            this.stock_status_idLabel.Name = "stock_status_idLabel";
            this.stock_status_idLabel.Size = new System.Drawing.Size(81, 13);
            this.stock_status_idLabel.TabIndex = 21;
            this.stock_status_idLabel.Text = "stock_status_id";
            // 
            // stock_status_idTextBox
            // 
            this.stock_status_idTextBox.Location = new System.Drawing.Point(141, 310);
            this.stock_status_idTextBox.Name = "stock_status_idTextBox";
            this.stock_status_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.stock_status_idTextBox.TabIndex = 22;
            this.stock_status_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.stock_status_idTextBox_Validating);
            // 
            // imageLabel
            // 
            this.imageLabel.AutoSize = true;
            this.imageLabel.Location = new System.Drawing.Point(96, 336);
            this.imageLabel.Name = "imageLabel";
            this.imageLabel.Size = new System.Drawing.Size(35, 13);
            this.imageLabel.TabIndex = 23;
            this.imageLabel.Text = "image";
            // 
            // imageTextBox
            // 
            this.imageTextBox.Location = new System.Drawing.Point(141, 336);
            this.imageTextBox.Name = "imageTextBox";
            this.imageTextBox.Size = new System.Drawing.Size(100, 20);
            this.imageTextBox.TabIndex = 24;
            this.imageTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.imageTextBox_Validating);
            // 
            // manufacturer_idLabel
            // 
            this.manufacturer_idLabel.AutoSize = true;
            this.manufacturer_idLabel.Location = new System.Drawing.Point(48, 362);
            this.manufacturer_idLabel.Name = "manufacturer_idLabel";
            this.manufacturer_idLabel.Size = new System.Drawing.Size(83, 13);
            this.manufacturer_idLabel.TabIndex = 25;
            this.manufacturer_idLabel.Text = "manufacturer_id";
            // 
            // manufacturer_idTextBox
            // 
            this.manufacturer_idTextBox.Location = new System.Drawing.Point(141, 362);
            this.manufacturer_idTextBox.Name = "manufacturer_idTextBox";
            this.manufacturer_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.manufacturer_idTextBox.TabIndex = 26;
            this.manufacturer_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.manufacturer_idTextBox_Validating);
            // 
            // shippingLabel
            // 
            this.shippingLabel.AutoSize = true;
            this.shippingLabel.Location = new System.Drawing.Point(85, 388);
            this.shippingLabel.Name = "shippingLabel";
            this.shippingLabel.Size = new System.Drawing.Size(46, 13);
            this.shippingLabel.TabIndex = 27;
            this.shippingLabel.Text = "shipping";
            // 
            // shippingCheckBox
            // 
            this.shippingCheckBox.AutoSize = true;
            this.shippingCheckBox.Location = new System.Drawing.Point(141, 391);
            this.shippingCheckBox.Name = "shippingCheckBox";
            this.shippingCheckBox.Size = new System.Drawing.Size(15, 14);
            this.shippingCheckBox.TabIndex = 28;
            this.shippingCheckBox.UseVisualStyleBackColor = true;
            // 
            // priceLabel
            // 
            this.priceLabel.AutoSize = true;
            this.priceLabel.Location = new System.Drawing.Point(101, 414);
            this.priceLabel.Name = "priceLabel";
            this.priceLabel.Size = new System.Drawing.Size(30, 13);
            this.priceLabel.TabIndex = 29;
            this.priceLabel.Text = "price";
            // 
            // priceTextBox
            // 
            this.priceTextBox.Location = new System.Drawing.Point(141, 414);
            this.priceTextBox.Name = "priceTextBox";
            this.priceTextBox.Size = new System.Drawing.Size(100, 20);
            this.priceTextBox.TabIndex = 30;
            this.priceTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.priceTextBox_Validating);
            // 
            // pointsLabel
            // 
            this.pointsLabel.AutoSize = true;
            this.pointsLabel.Location = new System.Drawing.Point(96, 440);
            this.pointsLabel.Name = "pointsLabel";
            this.pointsLabel.Size = new System.Drawing.Size(35, 13);
            this.pointsLabel.TabIndex = 31;
            this.pointsLabel.Text = "points";
            // 
            // pointsTextBox
            // 
            this.pointsTextBox.Location = new System.Drawing.Point(141, 440);
            this.pointsTextBox.Name = "pointsTextBox";
            this.pointsTextBox.Size = new System.Drawing.Size(100, 20);
            this.pointsTextBox.TabIndex = 32;
            this.pointsTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.pointsTextBox_Validating);
            // 
            // tax_class_idLabel
            // 
            this.tax_class_idLabel.AutoSize = true;
            this.tax_class_idLabel.Location = new System.Drawing.Point(367, 50);
            this.tax_class_idLabel.Name = "tax_class_idLabel";
            this.tax_class_idLabel.Size = new System.Drawing.Size(65, 13);
            this.tax_class_idLabel.TabIndex = 33;
            this.tax_class_idLabel.Text = "tax_class_id";
            // 
            // tax_class_idTextBox
            // 
            this.tax_class_idTextBox.Location = new System.Drawing.Point(442, 50);
            this.tax_class_idTextBox.Name = "tax_class_idTextBox";
            this.tax_class_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.tax_class_idTextBox.TabIndex = 34;
            this.tax_class_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.tax_class_idTextBox_Validating);
            // 
            // date_availableLabel
            // 
            this.date_availableLabel.AutoSize = true;
            this.date_availableLabel.Location = new System.Drawing.Point(356, 76);
            this.date_availableLabel.Name = "date_availableLabel";
            this.date_availableLabel.Size = new System.Drawing.Size(76, 13);
            this.date_availableLabel.TabIndex = 35;
            this.date_availableLabel.Text = "date_available";
            // 
            // date_available_dateTimePicker
            // 
            this.date_available_dateTimePicker.CustomFormat = "dd/MM/yyyy";
            this.date_available_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.date_available_dateTimePicker.Location = new System.Drawing.Point(442, 76);
            this.date_available_dateTimePicker.Name = "date_available_dateTimePicker";
            this.date_available_dateTimePicker.Size = new System.Drawing.Size(200, 20);
            this.date_available_dateTimePicker.TabIndex = 36;
            this.date_available_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
            // 
            // weightLabel
            // 
            this.weightLabel.AutoSize = true;
            this.weightLabel.Location = new System.Drawing.Point(394, 102);
            this.weightLabel.Name = "weightLabel";
            this.weightLabel.Size = new System.Drawing.Size(38, 13);
            this.weightLabel.TabIndex = 37;
            this.weightLabel.Text = "weight";
            // 
            // weightTextBox
            // 
            this.weightTextBox.Location = new System.Drawing.Point(442, 102);
            this.weightTextBox.Name = "weightTextBox";
            this.weightTextBox.Size = new System.Drawing.Size(100, 20);
            this.weightTextBox.TabIndex = 38;
            this.weightTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.weightTextBox_Validating);
            // 
            // weight_class_idLabel
            // 
            this.weight_class_idLabel.AutoSize = true;
            this.weight_class_idLabel.Location = new System.Drawing.Point(350, 128);
            this.weight_class_idLabel.Name = "weight_class_idLabel";
            this.weight_class_idLabel.Size = new System.Drawing.Size(82, 13);
            this.weight_class_idLabel.TabIndex = 39;
            this.weight_class_idLabel.Text = "weight_class_id";
            // 
            // weight_class_idTextBox
            // 
            this.weight_class_idTextBox.Location = new System.Drawing.Point(442, 128);
            this.weight_class_idTextBox.Name = "weight_class_idTextBox";
            this.weight_class_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.weight_class_idTextBox.TabIndex = 40;
            this.weight_class_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.weight_class_idTextBox_Validating);
            // 
            // lengthLabel
            // 
            this.lengthLabel.AutoSize = true;
            this.lengthLabel.Location = new System.Drawing.Point(396, 154);
            this.lengthLabel.Name = "lengthLabel";
            this.lengthLabel.Size = new System.Drawing.Size(36, 13);
            this.lengthLabel.TabIndex = 41;
            this.lengthLabel.Text = "length";
            // 
            // lengthTextBox
            // 
            this.lengthTextBox.Location = new System.Drawing.Point(442, 154);
            this.lengthTextBox.Name = "lengthTextBox";
            this.lengthTextBox.Size = new System.Drawing.Size(100, 20);
            this.lengthTextBox.TabIndex = 42;
            this.lengthTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.lengthTextBox_Validating);
            // 
            // widthLabel
            // 
            this.widthLabel.AutoSize = true;
            this.widthLabel.Location = new System.Drawing.Point(400, 180);
            this.widthLabel.Name = "widthLabel";
            this.widthLabel.Size = new System.Drawing.Size(32, 13);
            this.widthLabel.TabIndex = 43;
            this.widthLabel.Text = "width";
            // 
            // widthTextBox
            // 
            this.widthTextBox.Location = new System.Drawing.Point(442, 180);
            this.widthTextBox.Name = "widthTextBox";
            this.widthTextBox.Size = new System.Drawing.Size(100, 20);
            this.widthTextBox.TabIndex = 44;
            this.widthTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.widthTextBox_Validating);
            // 
            // heightLabel
            // 
            this.heightLabel.AutoSize = true;
            this.heightLabel.Location = new System.Drawing.Point(396, 206);
            this.heightLabel.Name = "heightLabel";
            this.heightLabel.Size = new System.Drawing.Size(36, 13);
            this.heightLabel.TabIndex = 45;
            this.heightLabel.Text = "height";
            // 
            // heightTextBox
            // 
            this.heightTextBox.Location = new System.Drawing.Point(442, 206);
            this.heightTextBox.Name = "heightTextBox";
            this.heightTextBox.Size = new System.Drawing.Size(100, 20);
            this.heightTextBox.TabIndex = 46;
            this.heightTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.heightTextBox_Validating);
            // 
            // length_class_idLabel
            // 
            this.length_class_idLabel.AutoSize = true;
            this.length_class_idLabel.Location = new System.Drawing.Point(352, 232);
            this.length_class_idLabel.Name = "length_class_idLabel";
            this.length_class_idLabel.Size = new System.Drawing.Size(80, 13);
            this.length_class_idLabel.TabIndex = 47;
            this.length_class_idLabel.Text = "length_class_id";
            // 
            // length_class_idTextBox
            // 
            this.length_class_idTextBox.Location = new System.Drawing.Point(442, 232);
            this.length_class_idTextBox.Name = "length_class_idTextBox";
            this.length_class_idTextBox.Size = new System.Drawing.Size(100, 20);
            this.length_class_idTextBox.TabIndex = 48;
            this.length_class_idTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.length_class_idTextBox_Validating);
            // 
            // subtractLabel
            // 
            this.subtractLabel.AutoSize = true;
            this.subtractLabel.Location = new System.Drawing.Point(387, 258);
            this.subtractLabel.Name = "subtractLabel";
            this.subtractLabel.Size = new System.Drawing.Size(45, 13);
            this.subtractLabel.TabIndex = 49;
            this.subtractLabel.Text = "subtract";
            // 
            // subtractCheckBox
            // 
            this.subtractCheckBox.AutoSize = true;
            this.subtractCheckBox.Location = new System.Drawing.Point(442, 261);
            this.subtractCheckBox.Name = "subtractCheckBox";
            this.subtractCheckBox.Size = new System.Drawing.Size(15, 14);
            this.subtractCheckBox.TabIndex = 50;
            this.subtractCheckBox.UseVisualStyleBackColor = true;
            // 
            // minimumLabel
            // 
            this.minimumLabel.AutoSize = true;
            this.minimumLabel.Location = new System.Drawing.Point(385, 284);
            this.minimumLabel.Name = "minimumLabel";
            this.minimumLabel.Size = new System.Drawing.Size(47, 13);
            this.minimumLabel.TabIndex = 51;
            this.minimumLabel.Text = "minimum";
            // 
            // minimumTextBox
            // 
            this.minimumTextBox.Location = new System.Drawing.Point(442, 284);
            this.minimumTextBox.Name = "minimumTextBox";
            this.minimumTextBox.Size = new System.Drawing.Size(100, 20);
            this.minimumTextBox.TabIndex = 52;
            this.minimumTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.minimumTextBox_Validating);
            // 
            // sort_orderLabel
            // 
            this.sort_orderLabel.AutoSize = true;
            this.sort_orderLabel.Location = new System.Drawing.Point(378, 310);
            this.sort_orderLabel.Name = "sort_orderLabel";
            this.sort_orderLabel.Size = new System.Drawing.Size(54, 13);
            this.sort_orderLabel.TabIndex = 53;
            this.sort_orderLabel.Text = "sort_order";
            // 
            // sort_orderTextBox
            // 
            this.sort_orderTextBox.Location = new System.Drawing.Point(442, 310);
            this.sort_orderTextBox.Name = "sort_orderTextBox";
            this.sort_orderTextBox.Size = new System.Drawing.Size(100, 20);
            this.sort_orderTextBox.TabIndex = 54;
            this.sort_orderTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.sort_orderTextBox_Validating);
            // 
            // statusLabel
            // 
            this.statusLabel.AutoSize = true;
            this.statusLabel.Location = new System.Drawing.Point(397, 336);
            this.statusLabel.Name = "statusLabel";
            this.statusLabel.Size = new System.Drawing.Size(35, 13);
            this.statusLabel.TabIndex = 55;
            this.statusLabel.Text = "status";
            // 
            // statusCheckBox
            // 
            this.statusCheckBox.AutoSize = true;
            this.statusCheckBox.Location = new System.Drawing.Point(442, 339);
            this.statusCheckBox.Name = "statusCheckBox";
            this.statusCheckBox.Size = new System.Drawing.Size(15, 14);
            this.statusCheckBox.TabIndex = 56;
            this.statusCheckBox.UseVisualStyleBackColor = true;
            // 
            // date_addedLabel
            // 
            this.date_addedLabel.AutoSize = true;
            this.date_addedLabel.Location = new System.Drawing.Point(368, 362);
            this.date_addedLabel.Name = "date_addedLabel";
            this.date_addedLabel.Size = new System.Drawing.Size(64, 13);
            this.date_addedLabel.TabIndex = 57;
            this.date_addedLabel.Text = "date_added";
            // 
            // date_added_dateTimePicker
            // 
            this.date_added_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm";
            this.date_added_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.date_added_dateTimePicker.Location = new System.Drawing.Point(442, 362);
            this.date_added_dateTimePicker.Name = "date_added_dateTimePicker";
            this.date_added_dateTimePicker.Size = new System.Drawing.Size(200, 20);
            this.date_added_dateTimePicker.TabIndex = 58;
            this.date_added_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
            // 
            // date_modifiedLabel
            // 
            this.date_modifiedLabel.AutoSize = true;
            this.date_modifiedLabel.Location = new System.Drawing.Point(359, 388);
            this.date_modifiedLabel.Name = "date_modifiedLabel";
            this.date_modifiedLabel.Size = new System.Drawing.Size(73, 13);
            this.date_modifiedLabel.TabIndex = 59;
            this.date_modifiedLabel.Text = "date_modified";
            // 
            // date_modified_dateTimePicker
            // 
            this.date_modified_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm";
            this.date_modified_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.date_modified_dateTimePicker.Location = new System.Drawing.Point(442, 388);
            this.date_modified_dateTimePicker.Name = "date_modified_dateTimePicker";
            this.date_modified_dateTimePicker.Size = new System.Drawing.Size(200, 20);
            this.date_modified_dateTimePicker.TabIndex = 60;
            this.date_modified_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
            // 
            // viewedLabel
            // 
            this.viewedLabel.AutoSize = true;
            this.viewedLabel.Location = new System.Drawing.Point(391, 414);
            this.viewedLabel.Name = "viewedLabel";
            this.viewedLabel.Size = new System.Drawing.Size(41, 13);
            this.viewedLabel.TabIndex = 61;
            this.viewedLabel.Text = "viewed";
            // 
            // viewedTextBox
            // 
            this.viewedTextBox.Location = new System.Drawing.Point(442, 414);
            this.viewedTextBox.Name = "viewedTextBox";
            this.viewedTextBox.Size = new System.Drawing.Size(100, 20);
            this.viewedTextBox.TabIndex = 62;
            this.viewedTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.viewedTextBox_Validating);
            // 
            // quantity_setLabel
            // 
            this.quantity_setLabel.AutoSize = true;
            this.quantity_setLabel.Location = new System.Drawing.Point(368, 440);
            this.quantity_setLabel.Name = "quantity_setLabel";
            this.quantity_setLabel.Size = new System.Drawing.Size(64, 13);
            this.quantity_setLabel.TabIndex = 63;
            this.quantity_setLabel.Text = "quantity_set";
            // 
            // quantity_setTextBox
            // 
            this.quantity_setTextBox.Location = new System.Drawing.Point(442, 440);
            this.quantity_setTextBox.Name = "quantity_setTextBox";
            this.quantity_setTextBox.Size = new System.Drawing.Size(100, 20);
            this.quantity_setTextBox.TabIndex = 64;
            this.quantity_setTextBox.Validating += new System.ComponentModel.CancelEventHandler(this.quantity_setTextBox_Validating);
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.Panel1);
            this.panel3.Controls.Add(this.panel4);
            this.panel3.Controls.Add(this.panel5);
            this.panel3.Controls.Add(this.panel6);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel3.Location = new System.Drawing.Point(0, 25);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(782, 441);
            this.panel3.TabIndex = 19;
            // 
            // panel4
            // 
            this.panel4.Dock = System.Windows.Forms.DockStyle.Right;
            this.panel4.Location = new System.Drawing.Point(772, 0);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(10, 431);
            this.panel4.TabIndex = 3;
            // 
            // panel5
            // 
            this.panel5.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel5.Location = new System.Drawing.Point(0, 0);
            this.panel5.Name = "panel5";
            this.panel5.Size = new System.Drawing.Size(10, 431);
            this.panel5.TabIndex = 5;
            // 
            // panel6
            // 
            this.panel6.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel6.Location = new System.Drawing.Point(0, 431);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(782, 10);
            this.panel6.TabIndex = 6;
            // 
            // frmoc_product
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.ClientSize = new System.Drawing.Size(782, 466);
            this.Controls.Add(this.panel3);
            this.Controls.Add(this.bindingNavigator1);
            this.Name = "frmoc_product";
            this.Text = "Oc_Product";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmoc_product_FormClosing);
            this.Load += new System.EventHandler(this.frmoc_product_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).EndInit();
            this.bindingNavigator1.ResumeLayout(false);
            this.bindingNavigator1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.oc_productBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.Panel1.ResumeLayout(false);
            this.Panel1.PerformLayout();
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

		}
		
		#endregion
		
		private System.Windows.Forms.BindingNavigator bindingNavigator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorAddNewItem;
		private System.Windows.Forms.ToolStripLabel bindingNavigatorCountItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorDeleteItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveFirstItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMovePreviousItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator;
		private System.Windows.Forms.ToolStripTextBox bindingNavigatorPositionItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveNextItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveLastItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator2;
		private System.Windows.Forms.ToolStripButton toolStripButton1;
		private System.Windows.Forms.ErrorProvider errorProvider1;
		private System.Windows.Forms.Panel Panel1;
		private System.Windows.Forms.BindingSource oc_productBindingSource;
		private System.Windows.Forms.TextBox product_idTextBox;
		private System.Windows.Forms.Label product_idLabel;
		private System.Windows.Forms.TextBox modelTextBox;
		private System.Windows.Forms.Label modelLabel;
		private System.Windows.Forms.TextBox skuTextBox;
		private System.Windows.Forms.Label skuLabel;
		private System.Windows.Forms.TextBox upcTextBox;
		private System.Windows.Forms.Label upcLabel;
		private System.Windows.Forms.TextBox eanTextBox;
		private System.Windows.Forms.Label eanLabel;
		private System.Windows.Forms.TextBox janTextBox;
		private System.Windows.Forms.Label janLabel;
		private System.Windows.Forms.TextBox isbnTextBox;
		private System.Windows.Forms.Label isbnLabel;
		private System.Windows.Forms.TextBox mpnTextBox;
		private System.Windows.Forms.Label mpnLabel;
		private System.Windows.Forms.TextBox locationTextBox;
		private System.Windows.Forms.Label locationLabel;
		private System.Windows.Forms.TextBox quantityTextBox;
		private System.Windows.Forms.Label quantityLabel;
		private System.Windows.Forms.TextBox stock_status_idTextBox;
		private System.Windows.Forms.Label stock_status_idLabel;
		private System.Windows.Forms.TextBox imageTextBox;
		private System.Windows.Forms.Label imageLabel;
		private System.Windows.Forms.TextBox manufacturer_idTextBox;
		private System.Windows.Forms.Label manufacturer_idLabel;
		private System.Windows.Forms.CheckBox shippingCheckBox;
		private System.Windows.Forms.Label shippingLabel;
		private System.Windows.Forms.TextBox priceTextBox;
		private System.Windows.Forms.Label priceLabel;
		private System.Windows.Forms.TextBox pointsTextBox;
		private System.Windows.Forms.Label pointsLabel;
		private System.Windows.Forms.TextBox tax_class_idTextBox;
		private System.Windows.Forms.Label tax_class_idLabel;
		private System.Windows.Forms.DateTimePicker date_available_dateTimePicker;
		private System.Windows.Forms.Label date_availableLabel;
		private System.Windows.Forms.TextBox weightTextBox;
		private System.Windows.Forms.Label weightLabel;
		private System.Windows.Forms.TextBox weight_class_idTextBox;
		private System.Windows.Forms.Label weight_class_idLabel;
		private System.Windows.Forms.TextBox lengthTextBox;
		private System.Windows.Forms.Label lengthLabel;
		private System.Windows.Forms.TextBox widthTextBox;
		private System.Windows.Forms.Label widthLabel;
		private System.Windows.Forms.TextBox heightTextBox;
		private System.Windows.Forms.Label heightLabel;
		private System.Windows.Forms.TextBox length_class_idTextBox;
		private System.Windows.Forms.Label length_class_idLabel;
		private System.Windows.Forms.CheckBox subtractCheckBox;
		private System.Windows.Forms.Label subtractLabel;
		private System.Windows.Forms.TextBox minimumTextBox;
		private System.Windows.Forms.Label minimumLabel;
		private System.Windows.Forms.TextBox sort_orderTextBox;
		private System.Windows.Forms.Label sort_orderLabel;
		private System.Windows.Forms.CheckBox statusCheckBox;
		private System.Windows.Forms.Label statusLabel;
		private System.Windows.Forms.DateTimePicker date_added_dateTimePicker;
		private System.Windows.Forms.Label date_addedLabel;
		private System.Windows.Forms.DateTimePicker date_modified_dateTimePicker;
		private System.Windows.Forms.Label date_modifiedLabel;
		private System.Windows.Forms.TextBox viewedTextBox;
		private System.Windows.Forms.Label viewedLabel;
		private System.Windows.Forms.TextBox quantity_setTextBox;
		private System.Windows.Forms.Label quantity_setLabel;
		private System.Windows.Forms.Panel panel3;
		private System.Windows.Forms.Panel panel4;
		private System.Windows.Forms.Panel panel5;
		private System.Windows.Forms.Panel panel6;
		
	}
}

