/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;

namespace MureOcart
{
	public partial class frmoc_product_description : Form
	{
		private Model1Entities ctx;
		
		public frmoc_product_description()
		{
			InitializeComponent();
		}
		
		private void frmoc_product_description_Load(object sender, EventArgs e)
		{
			ctx = new Model1Entities();
			ctx.oc_product_description.Load();
			BindingList<oc_product_description> _entities = ctx.oc_product_description.Local.ToBindingList();
			oc_product_descriptionBindingSource.DataSource = _entities;
			this.product_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_product_descriptionBindingSource, "product_id", true ));
			this.language_idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_product_descriptionBindingSource, "language_id", true ));
			this.nameTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_product_descriptionBindingSource, "name", true ));
			this.descriptionTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_product_descriptionBindingSource, "description", true ));
			this.meta_descriptionTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_product_descriptionBindingSource, "meta_description", true ));
			this.meta_keywordTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_product_descriptionBindingSource, "meta_keyword", true ));
			this.tagTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.oc_product_descriptionBindingSource, "tag", true ));
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			oc_product_descriptionBindingSource.EndEdit();
			ctx.SaveChanges();
			
		}
		
		private void frmoc_product_description_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void product_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( product_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( product_idTextBox, "The field product_id is required" ); 
			}
			int v;
			string s = product_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( product_idTextBox, "The field product_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( product_idTextBox, "" ); } 
		}
		
		private void language_idTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( language_idTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( language_idTextBox, "The field language_id is required" ); 
			}
			int v;
			string s = language_idTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( language_idTextBox, "The field language_id must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( language_idTextBox, "" ); } 
		}
		
		private void nameTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( nameTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( nameTextBox, "The field name is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( nameTextBox, "" ); } 
		}
		
		private void descriptionTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( descriptionTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( descriptionTextBox, "The field description is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( descriptionTextBox, "" ); } 
		}
		
		private void meta_descriptionTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( meta_descriptionTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( meta_descriptionTextBox, "The field meta_description is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( meta_descriptionTextBox, "" ); } 
		}
		
		private void meta_keywordTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( meta_keywordTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( meta_keywordTextBox, "The field meta_keyword is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( meta_keywordTextBox, "" ); } 
		}
		
		private void tagTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( tagTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( tagTextBox, "The field tag is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( tagTextBox, "" ); } 
		}
		
		
		
		
		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			oc_product_descriptionBindingSource.AddNew();
		}
	}
}
