//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MureOcart
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Entities : DbContext
    {
        public Model1Entities()
            : base("name=Model1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<oc_category> oc_category { get; set; }
        public virtual DbSet<oc_category_description> oc_category_description { get; set; }
        public virtual DbSet<oc_category_path> oc_category_path { get; set; }
        public virtual DbSet<oc_category_to_store> oc_category_to_store { get; set; }
        public virtual DbSet<oc_order> oc_order { get; set; }
        public virtual DbSet<oc_order_history> oc_order_history { get; set; }
        public virtual DbSet<oc_order_product> oc_order_product { get; set; }
        public virtual DbSet<oc_order_total> oc_order_total { get; set; }
        public virtual DbSet<oc_product> oc_product { get; set; }
        public virtual DbSet<oc_product_description> oc_product_description { get; set; }
        public virtual DbSet<oc_product_special> oc_product_special { get; set; }
        public virtual DbSet<oc_product_to_category> oc_product_to_category { get; set; }
        public virtual DbSet<oc_product_to_store> oc_product_to_store { get; set; }
        public virtual DbSet<oc_url_alias> oc_url_alias { get; set; }
    }
}
