//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MureOcart
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_url_alias
    {
        public int url_alias_id { get; set; }
        public string query { get; set; }
        public string keyword { get; set; }
    }
}
